// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: brick_storage.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrickStorageScope int32

const (
	BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED BrickStorageScope = 0
	BrickStorageScope_BRICK_STORAGE_SCOPE_USER        BrickStorageScope = 1
	BrickStorageScope_BRICK_STORAGE_SCOPE_LOCAL       BrickStorageScope = 2
	BrickStorageScope_BRICK_STORAGE_SCOPE_SECRET      BrickStorageScope = 3
)

// Enum value maps for BrickStorageScope.
var (
	BrickStorageScope_name = map[int32]string{
		0: "BRICK_STORAGE_SCOPE_UNSPECIFIED",
		1: "BRICK_STORAGE_SCOPE_USER",
		2: "BRICK_STORAGE_SCOPE_LOCAL",
		3: "BRICK_STORAGE_SCOPE_SECRET",
	}
	BrickStorageScope_value = map[string]int32{
		"BRICK_STORAGE_SCOPE_UNSPECIFIED": 0,
		"BRICK_STORAGE_SCOPE_USER":        1,
		"BRICK_STORAGE_SCOPE_LOCAL":       2,
		"BRICK_STORAGE_SCOPE_SECRET":      3,
	}
)

func (x BrickStorageScope) Enum() *BrickStorageScope {
	p := new(BrickStorageScope)
	*p = x
	return p
}

func (x BrickStorageScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrickStorageScope) Descriptor() protoreflect.EnumDescriptor {
	return file_brick_storage_proto_enumTypes[0].Descriptor()
}

func (BrickStorageScope) Type() protoreflect.EnumType {
	return &file_brick_storage_proto_enumTypes[0]
}

func (x BrickStorageScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrickStorageScope.Descriptor instead.
func (BrickStorageScope) EnumDescriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{0}
}

type BrickStorageKvKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageKvKeyRequest) Reset() {
	*x = BrickStorageKvKeyRequest{}
	mi := &file_brick_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageKvKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageKvKeyRequest) ProtoMessage() {}

func (x *BrickStorageKvKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageKvKeyRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageKvKeyRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{0}
}

func (x *BrickStorageKvKeyRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageKvKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type BrickStorageKvGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageKvGetRequest) Reset() {
	*x = BrickStorageKvGetRequest{}
	mi := &file_brick_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageKvGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageKvGetRequest) ProtoMessage() {}

func (x *BrickStorageKvGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageKvGetRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageKvGetRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{1}
}

func (x *BrickStorageKvGetRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageKvGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type BrickStorageKvGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         *BrickValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageKvGetResponse) Reset() {
	*x = BrickStorageKvGetResponse{}
	mi := &file_brick_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageKvGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageKvGetResponse) ProtoMessage() {}

func (x *BrickStorageKvGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageKvGetResponse.ProtoReflect.Descriptor instead.
func (*BrickStorageKvGetResponse) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{2}
}

func (x *BrickStorageKvGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *BrickStorageKvGetResponse) GetValue() *BrickValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type BrickStorageKvSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *BrickValue            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageKvSetRequest) Reset() {
	*x = BrickStorageKvSetRequest{}
	mi := &file_brick_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageKvSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageKvSetRequest) ProtoMessage() {}

func (x *BrickStorageKvSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageKvSetRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageKvSetRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{3}
}

func (x *BrickStorageKvSetRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageKvSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BrickStorageKvSetRequest) GetValue() *BrickValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type BrickStorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageDeleteResponse) Reset() {
	*x = BrickStorageDeleteResponse{}
	mi := &file_brick_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageDeleteResponse) ProtoMessage() {}

func (x *BrickStorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*BrickStorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{4}
}

func (x *BrickStorageDeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type BrickStorageHasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageHasResponse) Reset() {
	*x = BrickStorageHasResponse{}
	mi := &file_brick_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageHasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageHasResponse) ProtoMessage() {}

func (x *BrickStorageHasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageHasResponse.ProtoReflect.Descriptor instead.
func (*BrickStorageHasResponse) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{5}
}

func (x *BrickStorageHasResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BrickStorageKvListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageKvListRequest) Reset() {
	*x = BrickStorageKvListRequest{}
	mi := &file_brick_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageKvListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageKvListRequest) ProtoMessage() {}

func (x *BrickStorageKvListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageKvListRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageKvListRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{6}
}

func (x *BrickStorageKvListRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageKvListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type BrickStorageKvListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageKvListResponse) Reset() {
	*x = BrickStorageKvListResponse{}
	mi := &file_brick_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageKvListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageKvListResponse) ProtoMessage() {}

func (x *BrickStorageKvListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageKvListResponse.ProtoReflect.Descriptor instead.
func (*BrickStorageKvListResponse) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{7}
}

func (x *BrickStorageKvListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BrickStorageWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageWatchRequest) Reset() {
	*x = BrickStorageWatchRequest{}
	mi := &file_brick_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageWatchRequest) ProtoMessage() {}

func (x *BrickStorageWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageWatchRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageWatchRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{8}
}

func (x *BrickStorageWatchRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageWatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BrickStorageWatchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type BrickStorageChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Doc           *BrickValue            `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageChangeEvent) Reset() {
	*x = BrickStorageChangeEvent{}
	mi := &file_brick_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageChangeEvent) ProtoMessage() {}

func (x *BrickStorageChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageChangeEvent.ProtoReflect.Descriptor instead.
func (*BrickStorageChangeEvent) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{9}
}

func (x *BrickStorageChangeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BrickStorageChangeEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrickStorageChangeEvent) GetDoc() *BrickValue {
	if x != nil {
		return x.Doc
	}
	return nil
}

type BrickStorageDocKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageDocKeyRequest) Reset() {
	*x = BrickStorageDocKeyRequest{}
	mi := &file_brick_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageDocKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageDocKeyRequest) ProtoMessage() {}

func (x *BrickStorageDocKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageDocKeyRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageDocKeyRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{10}
}

func (x *BrickStorageDocKeyRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageDocKeyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BrickStorageDocKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BrickStorageCreateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Data          *BrickValue            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageCreateDocRequest) Reset() {
	*x = BrickStorageCreateDocRequest{}
	mi := &file_brick_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageCreateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageCreateDocRequest) ProtoMessage() {}

func (x *BrickStorageCreateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageCreateDocRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageCreateDocRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{11}
}

func (x *BrickStorageCreateDocRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageCreateDocRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BrickStorageCreateDocRequest) GetData() *BrickValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type BrickStoragePutDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Doc           *BrickValue            `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStoragePutDocRequest) Reset() {
	*x = BrickStoragePutDocRequest{}
	mi := &file_brick_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStoragePutDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStoragePutDocRequest) ProtoMessage() {}

func (x *BrickStoragePutDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStoragePutDocRequest.ProtoReflect.Descriptor instead.
func (*BrickStoragePutDocRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{12}
}

func (x *BrickStoragePutDocRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStoragePutDocRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BrickStoragePutDocRequest) GetDoc() *BrickValue {
	if x != nil {
		return x.Doc
	}
	return nil
}

type BrickStorageUpdateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Patch         *BrickValue            `protobuf:"bytes,4,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageUpdateDocRequest) Reset() {
	*x = BrickStorageUpdateDocRequest{}
	mi := &file_brick_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageUpdateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageUpdateDocRequest) ProtoMessage() {}

func (x *BrickStorageUpdateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageUpdateDocRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageUpdateDocRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{13}
}

func (x *BrickStorageUpdateDocRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageUpdateDocRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BrickStorageUpdateDocRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrickStorageUpdateDocRequest) GetPatch() *BrickValue {
	if x != nil {
		return x.Patch
	}
	return nil
}

type BrickStorageGetDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Doc           *BrickStorageDoc       `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageGetDocResponse) Reset() {
	*x = BrickStorageGetDocResponse{}
	mi := &file_brick_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageGetDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageGetDocResponse) ProtoMessage() {}

func (x *BrickStorageGetDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageGetDocResponse.ProtoReflect.Descriptor instead.
func (*BrickStorageGetDocResponse) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{14}
}

func (x *BrickStorageGetDocResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *BrickStorageGetDocResponse) GetDoc() *BrickStorageDoc {
	if x != nil {
		return x.Doc
	}
	return nil
}

type BrickStorageDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Data          *BrickValue            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageDoc) Reset() {
	*x = BrickStorageDoc{}
	mi := &file_brick_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageDoc) ProtoMessage() {}

func (x *BrickStorageDoc) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageDoc.ProtoReflect.Descriptor instead.
func (*BrickStorageDoc) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{15}
}

func (x *BrickStorageDoc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrickStorageDoc) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *BrickStorageDoc) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *BrickStorageDoc) GetData() *BrickValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type BrickStorageListDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         BrickStorageScope      `protobuf:"varint,1,opt,name=scope,proto3,enum=brickly.runtime.v1.BrickStorageScope" json:"scope,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Equals        *BrickValue            `protobuf:"bytes,4,opt,name=equals,proto3" json:"equals,omitempty"`
	Limit         *uint32                `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	After         string                 `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageListDocsRequest) Reset() {
	*x = BrickStorageListDocsRequest{}
	mi := &file_brick_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageListDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageListDocsRequest) ProtoMessage() {}

func (x *BrickStorageListDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageListDocsRequest.ProtoReflect.Descriptor instead.
func (*BrickStorageListDocsRequest) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{16}
}

func (x *BrickStorageListDocsRequest) GetScope() BrickStorageScope {
	if x != nil {
		return x.Scope
	}
	return BrickStorageScope_BRICK_STORAGE_SCOPE_UNSPECIFIED
}

func (x *BrickStorageListDocsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BrickStorageListDocsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *BrickStorageListDocsRequest) GetEquals() *BrickValue {
	if x != nil {
		return x.Equals
	}
	return nil
}

func (x *BrickStorageListDocsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *BrickStorageListDocsRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type BrickStorageListDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          []*BrickStorageDoc     `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageListDocsResponse) Reset() {
	*x = BrickStorageListDocsResponse{}
	mi := &file_brick_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageListDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageListDocsResponse) ProtoMessage() {}

func (x *BrickStorageListDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageListDocsResponse.ProtoReflect.Descriptor instead.
func (*BrickStorageListDocsResponse) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{17}
}

func (x *BrickStorageListDocsResponse) GetDocs() []*BrickStorageDoc {
	if x != nil {
		return x.Docs
	}
	return nil
}

type BrickStorageStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     uint64                 `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	QuotaBytes    uint64                 `protobuf:"varint,2,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	SignedIn      bool                   `protobuf:"varint,3,opt,name=signed_in,json=signedIn,proto3" json:"signed_in,omitempty"`
	LastSyncedAt  *int64                 `protobuf:"varint,4,opt,name=last_synced_at,json=lastSyncedAt,proto3,oneof" json:"last_synced_at,omitempty"`
	PendingWrites uint32                 `protobuf:"varint,5,opt,name=pending_writes,json=pendingWrites,proto3" json:"pending_writes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickStorageStatus) Reset() {
	*x = BrickStorageStatus{}
	mi := &file_brick_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickStorageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickStorageStatus) ProtoMessage() {}

func (x *BrickStorageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_brick_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickStorageStatus.ProtoReflect.Descriptor instead.
func (*BrickStorageStatus) Descriptor() ([]byte, []int) {
	return file_brick_storage_proto_rawDescGZIP(), []int{18}
}

func (x *BrickStorageStatus) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *BrickStorageStatus) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *BrickStorageStatus) GetSignedIn() bool {
	if x != nil {
		return x.SignedIn
	}
	return false
}

func (x *BrickStorageStatus) GetLastSyncedAt() int64 {
	if x != nil && x.LastSyncedAt != nil {
		return *x.LastSyncedAt
	}
	return 0
}

func (x *BrickStorageStatus) GetPendingWrites() uint32 {
	if x != nil {
		return x.PendingWrites
	}
	return 0
}

var File_brick_storage_proto protoreflect.FileDescriptor

const file_brick_storage_proto_rawDesc = "" +
	"\n" +
	"\x13brick_storage.proto\x12\x12brickly.runtime.v1\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"i\n" +
	"\x18BrickStorageKvKeyRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"i\n" +
	"\x18BrickStorageKvGetRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"g\n" +
	"\x19BrickStorageKvGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05value\"\x9f\x01\n" +
	"\x18BrickStorageKvSetRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x03 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05value\"6\n" +
	"\x1aBrickStorageDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"/\n" +
	"\x17BrickStorageHasResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\"p\n" +
	"\x19BrickStorageKvListRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"0\n" +
	"\x1aBrickStorageKvListResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x8f\x01\n" +
	"\x18BrickStorageWatchRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"o\n" +
	"\x17BrickStorageChangeEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x120\n" +
	"\x03doc\x18\x03 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x03doc\"\x88\x01\n" +
	"\x19BrickStorageDocKeyRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xaf\x01\n" +
	"\x1cBrickStorageCreateDocRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x04data\"\xaa\x01\n" +
	"\x19BrickStoragePutDocRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x120\n" +
	"\x03doc\x18\x03 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x03doc\"\xc1\x01\n" +
	"\x1cBrickStorageUpdateDocRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x124\n" +
	"\x05patch\x18\x04 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05patch\"i\n" +
	"\x1aBrickStorageGetDocResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x125\n" +
	"\x03doc\x18\x02 \x01(\v2#.brickly.runtime.v1.BrickStorageDocR\x03doc\"\x90\x01\n" +
	"\x0fBrickStorageDoc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x122\n" +
	"\x04data\x18\x04 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x04data\"\x85\x02\n" +
	"\x1bBrickStorageListDocsRequest\x12;\n" +
	"\x05scope\x18\x01 \x01(\x0e2%.brickly.runtime.v1.BrickStorageScopeR\x05scope\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x126\n" +
	"\x06equals\x18\x04 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x06equals\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x14\n" +
	"\x05after\x18\x06 \x01(\tR\x05afterB\b\n" +
	"\x06_limit\"W\n" +
	"\x1cBrickStorageListDocsResponse\x127\n" +
	"\x04docs\x18\x01 \x03(\v2#.brickly.runtime.v1.BrickStorageDocR\x04docs\"\xd6\x01\n" +
	"\x12BrickStorageStatus\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vquota_bytes\x18\x02 \x01(\x04R\n" +
	"quotaBytes\x12\x1b\n" +
	"\tsigned_in\x18\x03 \x01(\bR\bsignedIn\x12)\n" +
	"\x0elast_synced_at\x18\x04 \x01(\x03H\x00R\flastSyncedAt\x88\x01\x01\x12%\n" +
	"\x0epending_writes\x18\x05 \x01(\rR\rpendingWritesB\x11\n" +
	"\x0f_last_synced_at*\x95\x01\n" +
	"\x11BrickStorageScope\x12#\n" +
	"\x1fBRICK_STORAGE_SCOPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BRICK_STORAGE_SCOPE_USER\x10\x01\x12\x1d\n" +
	"\x19BRICK_STORAGE_SCOPE_LOCAL\x10\x02\x12\x1e\n" +
	"\x1aBRICK_STORAGE_SCOPE_SECRET\x10\x032\x87\v\n" +
	"\x13BrickStorageService\x12d\n" +
	"\x05KvGet\x12,.brickly.runtime.v1.BrickStorageKvGetRequest\x1a-.brickly.runtime.v1.BrickStorageKvGetResponse\x12M\n" +
	"\x05KvSet\x12,.brickly.runtime.v1.BrickStorageKvSetRequest\x1a\x16.google.protobuf.Empty\x12h\n" +
	"\bKvDelete\x12,.brickly.runtime.v1.BrickStorageKvKeyRequest\x1a..brickly.runtime.v1.BrickStorageDeleteResponse\x12b\n" +
	"\x05KvHas\x12,.brickly.runtime.v1.BrickStorageKvKeyRequest\x1a+.brickly.runtime.v1.BrickStorageHasResponse\x12g\n" +
	"\x06KvList\x12-.brickly.runtime.v1.BrickStorageKvListRequest\x1a..brickly.runtime.v1.BrickStorageKvListResponse\x12f\n" +
	"\aKvWatch\x12,.brickly.runtime.v1.BrickStorageWatchRequest\x1a+.brickly.runtime.v1.BrickStorageChangeEvent0\x01\x12b\n" +
	"\tCreateDoc\x120.brickly.runtime.v1.BrickStorageCreateDocRequest\x1a#.brickly.runtime.v1.BrickStorageDoc\x12g\n" +
	"\x06GetDoc\x12-.brickly.runtime.v1.BrickStorageDocKeyRequest\x1a..brickly.runtime.v1.BrickStorageGetDocResponse\x12\\\n" +
	"\x06PutDoc\x12-.brickly.runtime.v1.BrickStoragePutDocRequest\x1a#.brickly.runtime.v1.BrickStorageDoc\x12b\n" +
	"\tUpdateDoc\x120.brickly.runtime.v1.BrickStorageUpdateDocRequest\x1a#.brickly.runtime.v1.BrickStorageDoc\x12j\n" +
	"\tDeleteDoc\x12-.brickly.runtime.v1.BrickStorageDocKeyRequest\x1a..brickly.runtime.v1.BrickStorageDeleteResponse\x12m\n" +
	"\bListDocs\x12/.brickly.runtime.v1.BrickStorageListDocsRequest\x1a0.brickly.runtime.v1.BrickStorageListDocsResponse\x12h\n" +
	"\tWatchDocs\x12,.brickly.runtime.v1.BrickStorageWatchRequest\x1a+.brickly.runtime.v1.BrickStorageChangeEvent0\x01\x12H\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a&.brickly.runtime.v1.BrickStorageStatusB\xc8\x01\n" +
	"\x16com.brickly.runtime.v1B\x11BrickStorageProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_brick_storage_proto_rawDescOnce sync.Once
	file_brick_storage_proto_rawDescData []byte
)

func file_brick_storage_proto_rawDescGZIP() []byte {
	file_brick_storage_proto_rawDescOnce.Do(func() {
		file_brick_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brick_storage_proto_rawDesc), len(file_brick_storage_proto_rawDesc)))
	})
	return file_brick_storage_proto_rawDescData
}

var file_brick_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_brick_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_brick_storage_proto_goTypes = []any{
	(BrickStorageScope)(0),               // 0: brickly.runtime.v1.BrickStorageScope
	(*BrickStorageKvKeyRequest)(nil),     // 1: brickly.runtime.v1.BrickStorageKvKeyRequest
	(*BrickStorageKvGetRequest)(nil),     // 2: brickly.runtime.v1.BrickStorageKvGetRequest
	(*BrickStorageKvGetResponse)(nil),    // 3: brickly.runtime.v1.BrickStorageKvGetResponse
	(*BrickStorageKvSetRequest)(nil),     // 4: brickly.runtime.v1.BrickStorageKvSetRequest
	(*BrickStorageDeleteResponse)(nil),   // 5: brickly.runtime.v1.BrickStorageDeleteResponse
	(*BrickStorageHasResponse)(nil),      // 6: brickly.runtime.v1.BrickStorageHasResponse
	(*BrickStorageKvListRequest)(nil),    // 7: brickly.runtime.v1.BrickStorageKvListRequest
	(*BrickStorageKvListResponse)(nil),   // 8: brickly.runtime.v1.BrickStorageKvListResponse
	(*BrickStorageWatchRequest)(nil),     // 9: brickly.runtime.v1.BrickStorageWatchRequest
	(*BrickStorageChangeEvent)(nil),      // 10: brickly.runtime.v1.BrickStorageChangeEvent
	(*BrickStorageDocKeyRequest)(nil),    // 11: brickly.runtime.v1.BrickStorageDocKeyRequest
	(*BrickStorageCreateDocRequest)(nil), // 12: brickly.runtime.v1.BrickStorageCreateDocRequest
	(*BrickStoragePutDocRequest)(nil),    // 13: brickly.runtime.v1.BrickStoragePutDocRequest
	(*BrickStorageUpdateDocRequest)(nil), // 14: brickly.runtime.v1.BrickStorageUpdateDocRequest
	(*BrickStorageGetDocResponse)(nil),   // 15: brickly.runtime.v1.BrickStorageGetDocResponse
	(*BrickStorageDoc)(nil),              // 16: brickly.runtime.v1.BrickStorageDoc
	(*BrickStorageListDocsRequest)(nil),  // 17: brickly.runtime.v1.BrickStorageListDocsRequest
	(*BrickStorageListDocsResponse)(nil), // 18: brickly.runtime.v1.BrickStorageListDocsResponse
	(*BrickStorageStatus)(nil),           // 19: brickly.runtime.v1.BrickStorageStatus
	(*BrickValue)(nil),                   // 20: brickly.runtime.v1.BrickValue
	(*emptypb.Empty)(nil),                // 21: google.protobuf.Empty
}
var file_brick_storage_proto_depIdxs = []int32{
	0,  // 0: brickly.runtime.v1.BrickStorageKvKeyRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	0,  // 1: brickly.runtime.v1.BrickStorageKvGetRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 2: brickly.runtime.v1.BrickStorageKvGetResponse.value:type_name -> brickly.runtime.v1.BrickValue
	0,  // 3: brickly.runtime.v1.BrickStorageKvSetRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 4: brickly.runtime.v1.BrickStorageKvSetRequest.value:type_name -> brickly.runtime.v1.BrickValue
	0,  // 5: brickly.runtime.v1.BrickStorageKvListRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	0,  // 6: brickly.runtime.v1.BrickStorageWatchRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 7: brickly.runtime.v1.BrickStorageChangeEvent.doc:type_name -> brickly.runtime.v1.BrickValue
	0,  // 8: brickly.runtime.v1.BrickStorageDocKeyRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	0,  // 9: brickly.runtime.v1.BrickStorageCreateDocRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 10: brickly.runtime.v1.BrickStorageCreateDocRequest.data:type_name -> brickly.runtime.v1.BrickValue
	0,  // 11: brickly.runtime.v1.BrickStoragePutDocRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 12: brickly.runtime.v1.BrickStoragePutDocRequest.doc:type_name -> brickly.runtime.v1.BrickValue
	0,  // 13: brickly.runtime.v1.BrickStorageUpdateDocRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 14: brickly.runtime.v1.BrickStorageUpdateDocRequest.patch:type_name -> brickly.runtime.v1.BrickValue
	16, // 15: brickly.runtime.v1.BrickStorageGetDocResponse.doc:type_name -> brickly.runtime.v1.BrickStorageDoc
	20, // 16: brickly.runtime.v1.BrickStorageDoc.data:type_name -> brickly.runtime.v1.BrickValue
	0,  // 17: brickly.runtime.v1.BrickStorageListDocsRequest.scope:type_name -> brickly.runtime.v1.BrickStorageScope
	20, // 18: brickly.runtime.v1.BrickStorageListDocsRequest.equals:type_name -> brickly.runtime.v1.BrickValue
	16, // 19: brickly.runtime.v1.BrickStorageListDocsResponse.docs:type_name -> brickly.runtime.v1.BrickStorageDoc
	2,  // 20: brickly.runtime.v1.BrickStorageService.KvGet:input_type -> brickly.runtime.v1.BrickStorageKvGetRequest
	4,  // 21: brickly.runtime.v1.BrickStorageService.KvSet:input_type -> brickly.runtime.v1.BrickStorageKvSetRequest
	1,  // 22: brickly.runtime.v1.BrickStorageService.KvDelete:input_type -> brickly.runtime.v1.BrickStorageKvKeyRequest
	1,  // 23: brickly.runtime.v1.BrickStorageService.KvHas:input_type -> brickly.runtime.v1.BrickStorageKvKeyRequest
	7,  // 24: brickly.runtime.v1.BrickStorageService.KvList:input_type -> brickly.runtime.v1.BrickStorageKvListRequest
	9,  // 25: brickly.runtime.v1.BrickStorageService.KvWatch:input_type -> brickly.runtime.v1.BrickStorageWatchRequest
	12, // 26: brickly.runtime.v1.BrickStorageService.CreateDoc:input_type -> brickly.runtime.v1.BrickStorageCreateDocRequest
	11, // 27: brickly.runtime.v1.BrickStorageService.GetDoc:input_type -> brickly.runtime.v1.BrickStorageDocKeyRequest
	13, // 28: brickly.runtime.v1.BrickStorageService.PutDoc:input_type -> brickly.runtime.v1.BrickStoragePutDocRequest
	14, // 29: brickly.runtime.v1.BrickStorageService.UpdateDoc:input_type -> brickly.runtime.v1.BrickStorageUpdateDocRequest
	11, // 30: brickly.runtime.v1.BrickStorageService.DeleteDoc:input_type -> brickly.runtime.v1.BrickStorageDocKeyRequest
	17, // 31: brickly.runtime.v1.BrickStorageService.ListDocs:input_type -> brickly.runtime.v1.BrickStorageListDocsRequest
	9,  // 32: brickly.runtime.v1.BrickStorageService.WatchDocs:input_type -> brickly.runtime.v1.BrickStorageWatchRequest
	21, // 33: brickly.runtime.v1.BrickStorageService.Status:input_type -> google.protobuf.Empty
	3,  // 34: brickly.runtime.v1.BrickStorageService.KvGet:output_type -> brickly.runtime.v1.BrickStorageKvGetResponse
	21, // 35: brickly.runtime.v1.BrickStorageService.KvSet:output_type -> google.protobuf.Empty
	5,  // 36: brickly.runtime.v1.BrickStorageService.KvDelete:output_type -> brickly.runtime.v1.BrickStorageDeleteResponse
	6,  // 37: brickly.runtime.v1.BrickStorageService.KvHas:output_type -> brickly.runtime.v1.BrickStorageHasResponse
	8,  // 38: brickly.runtime.v1.BrickStorageService.KvList:output_type -> brickly.runtime.v1.BrickStorageKvListResponse
	10, // 39: brickly.runtime.v1.BrickStorageService.KvWatch:output_type -> brickly.runtime.v1.BrickStorageChangeEvent
	16, // 40: brickly.runtime.v1.BrickStorageService.CreateDoc:output_type -> brickly.runtime.v1.BrickStorageDoc
	15, // 41: brickly.runtime.v1.BrickStorageService.GetDoc:output_type -> brickly.runtime.v1.BrickStorageGetDocResponse
	16, // 42: brickly.runtime.v1.BrickStorageService.PutDoc:output_type -> brickly.runtime.v1.BrickStorageDoc
	16, // 43: brickly.runtime.v1.BrickStorageService.UpdateDoc:output_type -> brickly.runtime.v1.BrickStorageDoc
	5,  // 44: brickly.runtime.v1.BrickStorageService.DeleteDoc:output_type -> brickly.runtime.v1.BrickStorageDeleteResponse
	18, // 45: brickly.runtime.v1.BrickStorageService.ListDocs:output_type -> brickly.runtime.v1.BrickStorageListDocsResponse
	10, // 46: brickly.runtime.v1.BrickStorageService.WatchDocs:output_type -> brickly.runtime.v1.BrickStorageChangeEvent
	19, // 47: brickly.runtime.v1.BrickStorageService.Status:output_type -> brickly.runtime.v1.BrickStorageStatus
	34, // [34:48] is the sub-list for method output_type
	20, // [20:34] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_brick_storage_proto_init() }
func file_brick_storage_proto_init() {
	if File_brick_storage_proto != nil {
		return
	}
	file_common_proto_init()
	file_brick_storage_proto_msgTypes[16].OneofWrappers = []any{}
	file_brick_storage_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brick_storage_proto_rawDesc), len(file_brick_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brick_storage_proto_goTypes,
		DependencyIndexes: file_brick_storage_proto_depIdxs,
		EnumInfos:         file_brick_storage_proto_enumTypes,
		MessageInfos:      file_brick_storage_proto_msgTypes,
	}.Build()
	File_brick_storage_proto = out.File
	file_brick_storage_proto_goTypes = nil
	file_brick_storage_proto_depIdxs = nil
}
