// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: brick_storage.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrickStorageService_KvGet_FullMethodName     = "/brickly.runtime.v1.BrickStorageService/KvGet"
	BrickStorageService_KvSet_FullMethodName     = "/brickly.runtime.v1.BrickStorageService/KvSet"
	BrickStorageService_KvDelete_FullMethodName  = "/brickly.runtime.v1.BrickStorageService/KvDelete"
	BrickStorageService_KvHas_FullMethodName     = "/brickly.runtime.v1.BrickStorageService/KvHas"
	BrickStorageService_KvList_FullMethodName    = "/brickly.runtime.v1.BrickStorageService/KvList"
	BrickStorageService_KvWatch_FullMethodName   = "/brickly.runtime.v1.BrickStorageService/KvWatch"
	BrickStorageService_CreateDoc_FullMethodName = "/brickly.runtime.v1.BrickStorageService/CreateDoc"
	BrickStorageService_GetDoc_FullMethodName    = "/brickly.runtime.v1.BrickStorageService/GetDoc"
	BrickStorageService_PutDoc_FullMethodName    = "/brickly.runtime.v1.BrickStorageService/PutDoc"
	BrickStorageService_UpdateDoc_FullMethodName = "/brickly.runtime.v1.BrickStorageService/UpdateDoc"
	BrickStorageService_DeleteDoc_FullMethodName = "/brickly.runtime.v1.BrickStorageService/DeleteDoc"
	BrickStorageService_ListDocs_FullMethodName  = "/brickly.runtime.v1.BrickStorageService/ListDocs"
	BrickStorageService_WatchDocs_FullMethodName = "/brickly.runtime.v1.BrickStorageService/WatchDocs"
	BrickStorageService_Status_FullMethodName    = "/brickly.runtime.v1.BrickStorageService/Status"
)

// BrickStorageServiceClient is the client API for BrickStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrickStorageService 是按 brickId + origin 隔离的本机持久存储。
// 身份只从 runtime token 取，请求体不得自报 brickId。
// 现有 StorageService 仍是会话内存短键值，语义不变。
type BrickStorageServiceClient interface {
	KvGet(ctx context.Context, in *BrickStorageKvGetRequest, opts ...grpc.CallOption) (*BrickStorageKvGetResponse, error)
	KvSet(ctx context.Context, in *BrickStorageKvSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KvDelete(ctx context.Context, in *BrickStorageKvKeyRequest, opts ...grpc.CallOption) (*BrickStorageDeleteResponse, error)
	KvHas(ctx context.Context, in *BrickStorageKvKeyRequest, opts ...grpc.CallOption) (*BrickStorageHasResponse, error)
	KvList(ctx context.Context, in *BrickStorageKvListRequest, opts ...grpc.CallOption) (*BrickStorageKvListResponse, error)
	KvWatch(ctx context.Context, in *BrickStorageWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrickStorageChangeEvent], error)
	CreateDoc(ctx context.Context, in *BrickStorageCreateDocRequest, opts ...grpc.CallOption) (*BrickStorageDoc, error)
	GetDoc(ctx context.Context, in *BrickStorageDocKeyRequest, opts ...grpc.CallOption) (*BrickStorageGetDocResponse, error)
	PutDoc(ctx context.Context, in *BrickStoragePutDocRequest, opts ...grpc.CallOption) (*BrickStorageDoc, error)
	UpdateDoc(ctx context.Context, in *BrickStorageUpdateDocRequest, opts ...grpc.CallOption) (*BrickStorageDoc, error)
	DeleteDoc(ctx context.Context, in *BrickStorageDocKeyRequest, opts ...grpc.CallOption) (*BrickStorageDeleteResponse, error)
	ListDocs(ctx context.Context, in *BrickStorageListDocsRequest, opts ...grpc.CallOption) (*BrickStorageListDocsResponse, error)
	WatchDocs(ctx context.Context, in *BrickStorageWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrickStorageChangeEvent], error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BrickStorageStatus, error)
}

type brickStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrickStorageServiceClient(cc grpc.ClientConnInterface) BrickStorageServiceClient {
	return &brickStorageServiceClient{cc}
}

func (c *brickStorageServiceClient) KvGet(ctx context.Context, in *BrickStorageKvGetRequest, opts ...grpc.CallOption) (*BrickStorageKvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageKvGetResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) KvSet(ctx context.Context, in *BrickStorageKvSetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BrickStorageService_KvSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) KvDelete(ctx context.Context, in *BrickStorageKvKeyRequest, opts ...grpc.CallOption) (*BrickStorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageDeleteResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_KvDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) KvHas(ctx context.Context, in *BrickStorageKvKeyRequest, opts ...grpc.CallOption) (*BrickStorageHasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageHasResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_KvHas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) KvList(ctx context.Context, in *BrickStorageKvListRequest, opts ...grpc.CallOption) (*BrickStorageKvListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageKvListResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_KvList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) KvWatch(ctx context.Context, in *BrickStorageWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrickStorageChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrickStorageService_ServiceDesc.Streams[0], BrickStorageService_KvWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BrickStorageWatchRequest, BrickStorageChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrickStorageService_KvWatchClient = grpc.ServerStreamingClient[BrickStorageChangeEvent]

func (c *brickStorageServiceClient) CreateDoc(ctx context.Context, in *BrickStorageCreateDocRequest, opts ...grpc.CallOption) (*BrickStorageDoc, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageDoc)
	err := c.cc.Invoke(ctx, BrickStorageService_CreateDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) GetDoc(ctx context.Context, in *BrickStorageDocKeyRequest, opts ...grpc.CallOption) (*BrickStorageGetDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageGetDocResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_GetDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) PutDoc(ctx context.Context, in *BrickStoragePutDocRequest, opts ...grpc.CallOption) (*BrickStorageDoc, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageDoc)
	err := c.cc.Invoke(ctx, BrickStorageService_PutDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) UpdateDoc(ctx context.Context, in *BrickStorageUpdateDocRequest, opts ...grpc.CallOption) (*BrickStorageDoc, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageDoc)
	err := c.cc.Invoke(ctx, BrickStorageService_UpdateDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) DeleteDoc(ctx context.Context, in *BrickStorageDocKeyRequest, opts ...grpc.CallOption) (*BrickStorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageDeleteResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_DeleteDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) ListDocs(ctx context.Context, in *BrickStorageListDocsRequest, opts ...grpc.CallOption) (*BrickStorageListDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageListDocsResponse)
	err := c.cc.Invoke(ctx, BrickStorageService_ListDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickStorageServiceClient) WatchDocs(ctx context.Context, in *BrickStorageWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrickStorageChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrickStorageService_ServiceDesc.Streams[1], BrickStorageService_WatchDocs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BrickStorageWatchRequest, BrickStorageChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrickStorageService_WatchDocsClient = grpc.ServerStreamingClient[BrickStorageChangeEvent]

func (c *brickStorageServiceClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BrickStorageStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrickStorageStatus)
	err := c.cc.Invoke(ctx, BrickStorageService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrickStorageServiceServer is the server API for BrickStorageService service.
// All implementations must embed UnimplementedBrickStorageServiceServer
// for forward compatibility.
//
// BrickStorageService 是按 brickId + origin 隔离的本机持久存储。
// 身份只从 runtime token 取，请求体不得自报 brickId。
// 现有 StorageService 仍是会话内存短键值，语义不变。
type BrickStorageServiceServer interface {
	KvGet(context.Context, *BrickStorageKvGetRequest) (*BrickStorageKvGetResponse, error)
	KvSet(context.Context, *BrickStorageKvSetRequest) (*emptypb.Empty, error)
	KvDelete(context.Context, *BrickStorageKvKeyRequest) (*BrickStorageDeleteResponse, error)
	KvHas(context.Context, *BrickStorageKvKeyRequest) (*BrickStorageHasResponse, error)
	KvList(context.Context, *BrickStorageKvListRequest) (*BrickStorageKvListResponse, error)
	KvWatch(*BrickStorageWatchRequest, grpc.ServerStreamingServer[BrickStorageChangeEvent]) error
	CreateDoc(context.Context, *BrickStorageCreateDocRequest) (*BrickStorageDoc, error)
	GetDoc(context.Context, *BrickStorageDocKeyRequest) (*BrickStorageGetDocResponse, error)
	PutDoc(context.Context, *BrickStoragePutDocRequest) (*BrickStorageDoc, error)
	UpdateDoc(context.Context, *BrickStorageUpdateDocRequest) (*BrickStorageDoc, error)
	DeleteDoc(context.Context, *BrickStorageDocKeyRequest) (*BrickStorageDeleteResponse, error)
	ListDocs(context.Context, *BrickStorageListDocsRequest) (*BrickStorageListDocsResponse, error)
	WatchDocs(*BrickStorageWatchRequest, grpc.ServerStreamingServer[BrickStorageChangeEvent]) error
	Status(context.Context, *emptypb.Empty) (*BrickStorageStatus, error)
	mustEmbedUnimplementedBrickStorageServiceServer()
}

// UnimplementedBrickStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrickStorageServiceServer struct{}

func (UnimplementedBrickStorageServiceServer) KvGet(context.Context, *BrickStorageKvGetRequest) (*BrickStorageKvGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedBrickStorageServiceServer) KvSet(context.Context, *BrickStorageKvSetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvSet not implemented")
}
func (UnimplementedBrickStorageServiceServer) KvDelete(context.Context, *BrickStorageKvKeyRequest) (*BrickStorageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvDelete not implemented")
}
func (UnimplementedBrickStorageServiceServer) KvHas(context.Context, *BrickStorageKvKeyRequest) (*BrickStorageHasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvHas not implemented")
}
func (UnimplementedBrickStorageServiceServer) KvList(context.Context, *BrickStorageKvListRequest) (*BrickStorageKvListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvList not implemented")
}
func (UnimplementedBrickStorageServiceServer) KvWatch(*BrickStorageWatchRequest, grpc.ServerStreamingServer[BrickStorageChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method KvWatch not implemented")
}
func (UnimplementedBrickStorageServiceServer) CreateDoc(context.Context, *BrickStorageCreateDocRequest) (*BrickStorageDoc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDoc not implemented")
}
func (UnimplementedBrickStorageServiceServer) GetDoc(context.Context, *BrickStorageDocKeyRequest) (*BrickStorageGetDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDoc not implemented")
}
func (UnimplementedBrickStorageServiceServer) PutDoc(context.Context, *BrickStoragePutDocRequest) (*BrickStorageDoc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutDoc not implemented")
}
func (UnimplementedBrickStorageServiceServer) UpdateDoc(context.Context, *BrickStorageUpdateDocRequest) (*BrickStorageDoc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDoc not implemented")
}
func (UnimplementedBrickStorageServiceServer) DeleteDoc(context.Context, *BrickStorageDocKeyRequest) (*BrickStorageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDoc not implemented")
}
func (UnimplementedBrickStorageServiceServer) ListDocs(context.Context, *BrickStorageListDocsRequest) (*BrickStorageListDocsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocs not implemented")
}
func (UnimplementedBrickStorageServiceServer) WatchDocs(*BrickStorageWatchRequest, grpc.ServerStreamingServer[BrickStorageChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchDocs not implemented")
}
func (UnimplementedBrickStorageServiceServer) Status(context.Context, *emptypb.Empty) (*BrickStorageStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedBrickStorageServiceServer) mustEmbedUnimplementedBrickStorageServiceServer() {}
func (UnimplementedBrickStorageServiceServer) testEmbeddedByValue()                             {}

// UnsafeBrickStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrickStorageServiceServer will
// result in compilation errors.
type UnsafeBrickStorageServiceServer interface {
	mustEmbedUnimplementedBrickStorageServiceServer()
}

func RegisterBrickStorageServiceServer(s grpc.ServiceRegistrar, srv BrickStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrickStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrickStorageService_ServiceDesc, srv)
}

func _BrickStorageService_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageKvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).KvGet(ctx, req.(*BrickStorageKvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_KvSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageKvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).KvSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_KvSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).KvSet(ctx, req.(*BrickStorageKvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_KvDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageKvKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).KvDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_KvDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).KvDelete(ctx, req.(*BrickStorageKvKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_KvHas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageKvKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).KvHas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_KvHas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).KvHas(ctx, req.(*BrickStorageKvKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_KvList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageKvListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).KvList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_KvList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).KvList(ctx, req.(*BrickStorageKvListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_KvWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BrickStorageWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrickStorageServiceServer).KvWatch(m, &grpc.GenericServerStream[BrickStorageWatchRequest, BrickStorageChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrickStorageService_KvWatchServer = grpc.ServerStreamingServer[BrickStorageChangeEvent]

func _BrickStorageService_CreateDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageCreateDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).CreateDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_CreateDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).CreateDoc(ctx, req.(*BrickStorageCreateDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_GetDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageDocKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).GetDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_GetDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).GetDoc(ctx, req.(*BrickStorageDocKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_PutDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStoragePutDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).PutDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_PutDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).PutDoc(ctx, req.(*BrickStoragePutDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_UpdateDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageUpdateDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).UpdateDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_UpdateDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).UpdateDoc(ctx, req.(*BrickStorageUpdateDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_DeleteDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageDocKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).DeleteDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_DeleteDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).DeleteDoc(ctx, req.(*BrickStorageDocKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_ListDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrickStorageListDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).ListDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_ListDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).ListDocs(ctx, req.(*BrickStorageListDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickStorageService_WatchDocs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BrickStorageWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrickStorageServiceServer).WatchDocs(m, &grpc.GenericServerStream[BrickStorageWatchRequest, BrickStorageChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrickStorageService_WatchDocsServer = grpc.ServerStreamingServer[BrickStorageChangeEvent]

func _BrickStorageService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickStorageServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickStorageService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickStorageServiceServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BrickStorageService_ServiceDesc is the grpc.ServiceDesc for BrickStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrickStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brickly.runtime.v1.BrickStorageService",
	HandlerType: (*BrickStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KvGet",
			Handler:    _BrickStorageService_KvGet_Handler,
		},
		{
			MethodName: "KvSet",
			Handler:    _BrickStorageService_KvSet_Handler,
		},
		{
			MethodName: "KvDelete",
			Handler:    _BrickStorageService_KvDelete_Handler,
		},
		{
			MethodName: "KvHas",
			Handler:    _BrickStorageService_KvHas_Handler,
		},
		{
			MethodName: "KvList",
			Handler:    _BrickStorageService_KvList_Handler,
		},
		{
			MethodName: "CreateDoc",
			Handler:    _BrickStorageService_CreateDoc_Handler,
		},
		{
			MethodName: "GetDoc",
			Handler:    _BrickStorageService_GetDoc_Handler,
		},
		{
			MethodName: "PutDoc",
			Handler:    _BrickStorageService_PutDoc_Handler,
		},
		{
			MethodName: "UpdateDoc",
			Handler:    _BrickStorageService_UpdateDoc_Handler,
		},
		{
			MethodName: "DeleteDoc",
			Handler:    _BrickStorageService_DeleteDoc_Handler,
		},
		{
			MethodName: "ListDocs",
			Handler:    _BrickStorageService_ListDocs_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _BrickStorageService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KvWatch",
			Handler:       _BrickStorageService_KvWatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchDocs",
			Handler:       _BrickStorageService_WatchDocs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "brick_storage.proto",
}
