// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: command.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Input         *BrickValue            `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *InvokeRequest) GetInput() *BrickValue {
	if x != nil {
		return x.Input
	}
	return nil
}

type InvokeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *BrickValue            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResult) Reset() {
	*x = InvokeResult{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResult) ProtoMessage() {}

func (x *InvokeResult) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResult.ProtoReflect.Descriptor instead.
func (*InvokeResult) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResult) GetResult() *BrickValue {
	if x != nil {
		return x.Result
	}
	return nil
}

// sequence 每个方向从 1 严格递增，只用于顺序校验和诊断。
// message_id / reply_to 为 16-byte 随机值，仅用于 interaction 内 request/reply 关联。
type FrameHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	MessageId     []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	ReplyTo       []byte                 `protobuf:"bytes,3,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameHeader) Reset() {
	*x = FrameHeader{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameHeader) ProtoMessage() {}

func (x *FrameHeader) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameHeader.ProtoReflect.Descriptor instead.
func (*FrameHeader) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *FrameHeader) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FrameHeader) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *FrameHeader) GetReplyTo() []byte {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

type OpenFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Input         *BrickValue            `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFrame) Reset() {
	*x = OpenFrame{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFrame) ProtoMessage() {}

func (x *OpenFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFrame.ProtoReflect.Descriptor instead.
func (*OpenFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *OpenFrame) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *OpenFrame) GetInput() *BrickValue {
	if x != nil {
		return x.Input
	}
	return nil
}

// opened 无业务 payload，必须是服务端第一帧。
type OpenedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenedFrame) Reset() {
	*x = OpenedFrame{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedFrame) ProtoMessage() {}

func (x *OpenedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedFrame.ProtoReflect.Descriptor instead.
func (*OpenedFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

type EventFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *BrickValue            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *EventFrame) GetPayload() *BrickValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RequestFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *BrickValue            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFrame) Reset() {
	*x = RequestFrame{}
	mi := &file_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFrame) ProtoMessage() {}

func (x *RequestFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFrame.ProtoReflect.Descriptor instead.
func (*RequestFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{6}
}

func (x *RequestFrame) GetPayload() *BrickValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CancelRequestFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequestFrame) Reset() {
	*x = CancelRequestFrame{}
	mi := &file_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequestFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequestFrame) ProtoMessage() {}

func (x *CancelRequestFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequestFrame.ProtoReflect.Descriptor instead.
func (*CancelRequestFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{7}
}

type ResponseFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ResponseFrame_Value
	//	*ResponseFrame_Error
	Outcome       isResponseFrame_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFrame) Reset() {
	*x = ResponseFrame{}
	mi := &file_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFrame) ProtoMessage() {}

func (x *ResponseFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFrame.ProtoReflect.Descriptor instead.
func (*ResponseFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseFrame) GetOutcome() isResponseFrame_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ResponseFrame) GetValue() *BrickValue {
	if x != nil {
		if x, ok := x.Outcome.(*ResponseFrame_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *ResponseFrame) GetError() *BrickError {
	if x != nil {
		if x, ok := x.Outcome.(*ResponseFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResponseFrame_Outcome interface {
	isResponseFrame_Outcome()
}

type ResponseFrame_Value struct {
	Value *BrickValue `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type ResponseFrame_Error struct {
	Error *BrickError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ResponseFrame_Value) isResponseFrame_Outcome() {}

func (*ResponseFrame_Error) isResponseFrame_Outcome() {}

type FinalFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *BrickValue            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalFrame) Reset() {
	*x = FinalFrame{}
	mi := &file_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalFrame) ProtoMessage() {}

func (x *FinalFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalFrame.ProtoReflect.Descriptor instead.
func (*FinalFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{9}
}

func (x *FinalFrame) GetResult() *BrickValue {
	if x != nil {
		return x.Result
	}
	return nil
}

type ClientFrame struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *FrameHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientFrame_Open
	//	*ClientFrame_Event
	//	*ClientFrame_Request
	//	*ClientFrame_CancelRequest
	Body          isClientFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{10}
}

func (x *ClientFrame) GetHeader() *FrameHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ClientFrame) GetBody() isClientFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientFrame) GetOpen() *OpenFrame {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ClientFrame) GetEvent() *EventFrame {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ClientFrame) GetRequest() *RequestFrame {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ClientFrame) GetCancelRequest() *CancelRequestFrame {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_CancelRequest); ok {
			return x.CancelRequest
		}
	}
	return nil
}

type isClientFrame_Body interface {
	isClientFrame_Body()
}

type ClientFrame_Open struct {
	Open *OpenFrame `protobuf:"bytes,10,opt,name=open,proto3,oneof"`
}

type ClientFrame_Event struct {
	Event *EventFrame `protobuf:"bytes,11,opt,name=event,proto3,oneof"`
}

type ClientFrame_Request struct {
	Request *RequestFrame `protobuf:"bytes,12,opt,name=request,proto3,oneof"`
}

type ClientFrame_CancelRequest struct {
	CancelRequest *CancelRequestFrame `protobuf:"bytes,13,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

func (*ClientFrame_Open) isClientFrame_Body() {}

func (*ClientFrame_Event) isClientFrame_Body() {}

func (*ClientFrame_Request) isClientFrame_Body() {}

func (*ClientFrame_CancelRequest) isClientFrame_Body() {}

type ServerFrame struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *FrameHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Opened
	//	*ServerFrame_Event
	//	*ServerFrame_Response
	//	*ServerFrame_Final
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{11}
}

func (x *ServerFrame) GetHeader() *FrameHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetOpened() *OpenedFrame {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *ServerFrame) GetEvent() *EventFrame {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerFrame) GetResponse() *ResponseFrame {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *ServerFrame) GetFinal() *FinalFrame {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Opened struct {
	Opened *OpenedFrame `protobuf:"bytes,10,opt,name=opened,proto3,oneof"`
}

type ServerFrame_Event struct {
	Event *EventFrame `protobuf:"bytes,11,opt,name=event,proto3,oneof"`
}

type ServerFrame_Response struct {
	Response *ResponseFrame `protobuf:"bytes,12,opt,name=response,proto3,oneof"`
}

type ServerFrame_Final struct {
	Final *FinalFrame `protobuf:"bytes,13,opt,name=final,proto3,oneof"`
}

func (*ServerFrame_Opened) isServerFrame_Body() {}

func (*ServerFrame_Event) isServerFrame_Body() {}

func (*ServerFrame_Response) isServerFrame_Body() {}

func (*ServerFrame_Final) isServerFrame_Body() {}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x12brickly.runtime.v1\x1a\fcommon.proto\x1a\verror.proto\"d\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x124\n" +
	"\x05input\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05input\"F\n" +
	"\fInvokeResult\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x06result\"\x89\x01\n" +
	"\vFrameHeader\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\"\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fH\x00R\tmessageId\x88\x01\x01\x12\x1e\n" +
	"\breply_to\x18\x03 \x01(\fH\x01R\areplyTo\x88\x01\x01B\r\n" +
	"\v_message_idB\v\n" +
	"\t_reply_to\"`\n" +
	"\tOpenFrame\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x124\n" +
	"\x05input\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05input\"\r\n" +
	"\vOpenedFrame\"F\n" +
	"\n" +
	"EventFrame\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\apayload\"H\n" +
	"\fRequestFrame\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\apayload\"\x14\n" +
	"\x12CancelRequestFrame\"\x8a\x01\n" +
	"\rResponseFrame\x126\n" +
	"\x05value\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueH\x00R\x05value\x126\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickErrorH\x00R\x05errorB\t\n" +
	"\aoutcome\"D\n" +
	"\n" +
	"FinalFrame\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x06result\"\xca\x02\n" +
	"\vClientFrame\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.brickly.runtime.v1.FrameHeaderR\x06header\x123\n" +
	"\x04open\x18\n" +
	" \x01(\v2\x1d.brickly.runtime.v1.OpenFrameH\x00R\x04open\x126\n" +
	"\x05event\x18\v \x01(\v2\x1e.brickly.runtime.v1.EventFrameH\x00R\x05event\x12<\n" +
	"\arequest\x18\f \x01(\v2 .brickly.runtime.v1.RequestFrameH\x00R\arequest\x12O\n" +
	"\x0ecancel_request\x18\r \x01(\v2&.brickly.runtime.v1.CancelRequestFrameH\x00R\rcancelRequestB\x06\n" +
	"\x04body\"\xba\x02\n" +
	"\vServerFrame\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.brickly.runtime.v1.FrameHeaderR\x06header\x129\n" +
	"\x06opened\x18\n" +
	" \x01(\v2\x1f.brickly.runtime.v1.OpenedFrameH\x00R\x06opened\x126\n" +
	"\x05event\x18\v \x01(\v2\x1e.brickly.runtime.v1.EventFrameH\x00R\x05event\x12?\n" +
	"\bresponse\x18\f \x01(\v2!.brickly.runtime.v1.ResponseFrameH\x00R\bresponse\x126\n" +
	"\x05final\x18\r \x01(\v2\x1e.brickly.runtime.v1.FinalFrameH\x00R\x05finalB\x06\n" +
	"\x04body2\xb6\x01\n" +
	"\x13BrickCommandService\x12M\n" +
	"\x06Invoke\x12!.brickly.runtime.v1.InvokeRequest\x1a .brickly.runtime.v1.InvokeResult\x12P\n" +
	"\bInteract\x12\x1f.brickly.runtime.v1.ClientFrame\x1a\x1f.brickly.runtime.v1.ServerFrame(\x010\x01B\xc3\x01\n" +
	"\x16com.brickly.runtime.v1B\fCommandProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_command_proto_goTypes = []any{
	(*InvokeRequest)(nil),      // 0: brickly.runtime.v1.InvokeRequest
	(*InvokeResult)(nil),       // 1: brickly.runtime.v1.InvokeResult
	(*FrameHeader)(nil),        // 2: brickly.runtime.v1.FrameHeader
	(*OpenFrame)(nil),          // 3: brickly.runtime.v1.OpenFrame
	(*OpenedFrame)(nil),        // 4: brickly.runtime.v1.OpenedFrame
	(*EventFrame)(nil),         // 5: brickly.runtime.v1.EventFrame
	(*RequestFrame)(nil),       // 6: brickly.runtime.v1.RequestFrame
	(*CancelRequestFrame)(nil), // 7: brickly.runtime.v1.CancelRequestFrame
	(*ResponseFrame)(nil),      // 8: brickly.runtime.v1.ResponseFrame
	(*FinalFrame)(nil),         // 9: brickly.runtime.v1.FinalFrame
	(*ClientFrame)(nil),        // 10: brickly.runtime.v1.ClientFrame
	(*ServerFrame)(nil),        // 11: brickly.runtime.v1.ServerFrame
	(*BrickValue)(nil),         // 12: brickly.runtime.v1.BrickValue
	(*BrickError)(nil),         // 13: brickly.runtime.v1.BrickError
}
var file_command_proto_depIdxs = []int32{
	12, // 0: brickly.runtime.v1.InvokeRequest.input:type_name -> brickly.runtime.v1.BrickValue
	12, // 1: brickly.runtime.v1.InvokeResult.result:type_name -> brickly.runtime.v1.BrickValue
	12, // 2: brickly.runtime.v1.OpenFrame.input:type_name -> brickly.runtime.v1.BrickValue
	12, // 3: brickly.runtime.v1.EventFrame.payload:type_name -> brickly.runtime.v1.BrickValue
	12, // 4: brickly.runtime.v1.RequestFrame.payload:type_name -> brickly.runtime.v1.BrickValue
	12, // 5: brickly.runtime.v1.ResponseFrame.value:type_name -> brickly.runtime.v1.BrickValue
	13, // 6: brickly.runtime.v1.ResponseFrame.error:type_name -> brickly.runtime.v1.BrickError
	12, // 7: brickly.runtime.v1.FinalFrame.result:type_name -> brickly.runtime.v1.BrickValue
	2,  // 8: brickly.runtime.v1.ClientFrame.header:type_name -> brickly.runtime.v1.FrameHeader
	3,  // 9: brickly.runtime.v1.ClientFrame.open:type_name -> brickly.runtime.v1.OpenFrame
	5,  // 10: brickly.runtime.v1.ClientFrame.event:type_name -> brickly.runtime.v1.EventFrame
	6,  // 11: brickly.runtime.v1.ClientFrame.request:type_name -> brickly.runtime.v1.RequestFrame
	7,  // 12: brickly.runtime.v1.ClientFrame.cancel_request:type_name -> brickly.runtime.v1.CancelRequestFrame
	2,  // 13: brickly.runtime.v1.ServerFrame.header:type_name -> brickly.runtime.v1.FrameHeader
	4,  // 14: brickly.runtime.v1.ServerFrame.opened:type_name -> brickly.runtime.v1.OpenedFrame
	5,  // 15: brickly.runtime.v1.ServerFrame.event:type_name -> brickly.runtime.v1.EventFrame
	8,  // 16: brickly.runtime.v1.ServerFrame.response:type_name -> brickly.runtime.v1.ResponseFrame
	9,  // 17: brickly.runtime.v1.ServerFrame.final:type_name -> brickly.runtime.v1.FinalFrame
	0,  // 18: brickly.runtime.v1.BrickCommandService.Invoke:input_type -> brickly.runtime.v1.InvokeRequest
	10, // 19: brickly.runtime.v1.BrickCommandService.Interact:input_type -> brickly.runtime.v1.ClientFrame
	1,  // 20: brickly.runtime.v1.BrickCommandService.Invoke:output_type -> brickly.runtime.v1.InvokeResult
	11, // 21: brickly.runtime.v1.BrickCommandService.Interact:output_type -> brickly.runtime.v1.ServerFrame
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_common_proto_init()
	file_error_proto_init()
	file_command_proto_msgTypes[2].OneofWrappers = []any{}
	file_command_proto_msgTypes[8].OneofWrappers = []any{
		(*ResponseFrame_Value)(nil),
		(*ResponseFrame_Error)(nil),
	}
	file_command_proto_msgTypes[10].OneofWrappers = []any{
		(*ClientFrame_Open)(nil),
		(*ClientFrame_Event)(nil),
		(*ClientFrame_Request)(nil),
		(*ClientFrame_CancelRequest)(nil),
	}
	file_command_proto_msgTypes[11].OneofWrappers = []any{
		(*ServerFrame_Opened)(nil),
		(*ServerFrame_Event)(nil),
		(*ServerFrame_Response)(nil),
		(*ServerFrame_Final)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
