// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BrickRef 是 Brick 的完整逻辑身份，不单独承担授权。
type BrickRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrickId       string                 `protobuf:"bytes,1,opt,name=brick_id,json=brickId,proto3" json:"brick_id,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickRef) Reset() {
	*x = BrickRef{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickRef) ProtoMessage() {}

func (x *BrickRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickRef.ProtoReflect.Descriptor instead.
func (*BrickRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *BrickRef) GetBrickId() string {
	if x != nil {
		return x.BrickId
	}
	return ""
}

func (x *BrickRef) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *BrickRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ResourceRef 是不可变资源描述。不含 bearer token 或 Host 路径。
// sha256 必须恰好 32 bytes。resource_id 格式为 res_ + 22 个 base64url 字符。
// name UTF-8 最多 255 bytes；media_type 最多 255 ASCII 且必须是可解析 MIME。
// expires_at 只供展示和快速失败，是否过期以 Host Catalog 为准。
type ResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MediaType     *string                `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3,oneof" json:"media_type,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRef) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceRef) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ResourceRef) GetMediaType() string {
	if x != nil && x.MediaType != nil {
		return *x.MediaType
	}
	return ""
}

func (x *ResourceRef) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ResourceRef) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ResourceRef) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// NullValue 表示显式 null。顶层无结果仅在 schema 为 false/null 时使用。
type NullValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type BrickList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BrickValue          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickList) Reset() {
	*x = BrickList{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickList) ProtoMessage() {}

func (x *BrickList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickList.ProtoReflect.Descriptor instead.
func (*BrickList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *BrickList) GetItems() []*BrickValue {
	if x != nil {
		return x.Items
	}
	return nil
}

// 使用 repeated field 保留插入顺序；业务不得依赖字段顺序。
// key 必须唯一且为有效 UTF-8。禁止使用 map，因为 protobuf map 不保证顺序。
type BrickObjectField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *BrickValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickObjectField) Reset() {
	*x = BrickObjectField{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickObjectField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickObjectField) ProtoMessage() {}

func (x *BrickObjectField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickObjectField.ProtoReflect.Descriptor instead.
func (*BrickObjectField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *BrickObjectField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BrickObjectField) GetValue() *BrickValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type BrickObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*BrickObjectField    `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickObject) Reset() {
	*x = BrickObject{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickObject) ProtoMessage() {}

func (x *BrickObject) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickObject.ProtoReflect.Descriptor instead.
func (*BrickObject) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *BrickObject) GetFields() []*BrickObjectField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// BrickValue 是动态命令值的稳定 wire 契约。
// integer 只接受 [-(2^53-1), 2^53-1]；number 必须有限，拒绝 NaN/Infinity/负零特殊语义。
// string 必须是有效 UTF-8。bytes 只用于小型二进制，受外层消息上限约束。
// 解码限制：最大深度 64、最多 100000 个 value node。
type BrickValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*BrickValue_NullValue
	//	*BrickValue_BoolValue
	//	*BrickValue_SafeIntegerValue
	//	*BrickValue_NumberValue
	//	*BrickValue_StringValue
	//	*BrickValue_BytesValue
	//	*BrickValue_ListValue
	//	*BrickValue_ObjectValue
	//	*BrickValue_ResourceValue
	Value         isBrickValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickValue) Reset() {
	*x = BrickValue{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickValue) ProtoMessage() {}

func (x *BrickValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickValue.ProtoReflect.Descriptor instead.
func (*BrickValue) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *BrickValue) GetValue() isBrickValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BrickValue) GetNullValue() *NullValue {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

func (x *BrickValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *BrickValue) GetSafeIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_SafeIntegerValue); ok {
			return x.SafeIntegerValue
		}
	}
	return 0
}

func (x *BrickValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *BrickValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *BrickValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *BrickValue) GetListValue() *BrickList {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *BrickValue) GetObjectValue() *BrickObject {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_ObjectValue); ok {
			return x.ObjectValue
		}
	}
	return nil
}

func (x *BrickValue) GetResourceValue() *ResourceRef {
	if x != nil {
		if x, ok := x.Value.(*BrickValue_ResourceValue); ok {
			return x.ResourceValue
		}
	}
	return nil
}

type isBrickValue_Value interface {
	isBrickValue_Value()
}

type BrickValue_NullValue struct {
	NullValue *NullValue `protobuf:"bytes,1,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type BrickValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type BrickValue_SafeIntegerValue struct {
	SafeIntegerValue int64 `protobuf:"zigzag64,3,opt,name=safe_integer_value,json=safeIntegerValue,proto3,oneof"`
}

type BrickValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,4,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type BrickValue_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type BrickValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type BrickValue_ListValue struct {
	ListValue *BrickList `protobuf:"bytes,7,opt,name=list_value,json=listValue,proto3,oneof"`
}

type BrickValue_ObjectValue struct {
	ObjectValue *BrickObject `protobuf:"bytes,8,opt,name=object_value,json=objectValue,proto3,oneof"`
}

type BrickValue_ResourceValue struct {
	ResourceValue *ResourceRef `protobuf:"bytes,9,opt,name=resource_value,json=resourceValue,proto3,oneof"`
}

func (*BrickValue_NullValue) isBrickValue_Value() {}

func (*BrickValue_BoolValue) isBrickValue_Value() {}

func (*BrickValue_SafeIntegerValue) isBrickValue_Value() {}

func (*BrickValue_NumberValue) isBrickValue_Value() {}

func (*BrickValue_StringValue) isBrickValue_Value() {}

func (*BrickValue_BytesValue) isBrickValue_Value() {}

func (*BrickValue_ListValue) isBrickValue_Value() {}

func (*BrickValue_ObjectValue) isBrickValue_Value() {}

func (*BrickValue_ResourceValue) isBrickValue_Value() {}

// TraceContext 可放入 gRPC metadata；payload 无权覆盖可信 parent。
type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentSpanId  *string                `protobuf:"bytes,2,opt,name=parent_span_id,json=parentSpanId,proto3,oneof" json:"parent_span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *TraceContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceContext) GetParentSpanId() string {
	if x != nil && x.ParentSpanId != nil {
		return *x.ParentSpanId
	}
	return ""
}

type RuntimePrincipalView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RuntimeHandleId string                 `protobuf:"bytes,1,opt,name=runtime_handle_id,json=runtimeHandleId,proto3" json:"runtime_handle_id,omitempty"`
	Brick           *BrickRef              `protobuf:"bytes,2,opt,name=brick,proto3" json:"brick,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimePrincipalView) Reset() {
	*x = RuntimePrincipalView{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimePrincipalView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimePrincipalView) ProtoMessage() {}

func (x *RuntimePrincipalView) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimePrincipalView.ProtoReflect.Descriptor instead.
func (*RuntimePrincipalView) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimePrincipalView) GetRuntimeHandleId() string {
	if x != nil {
		return x.RuntimeHandleId
	}
	return ""
}

func (x *RuntimePrincipalView) GetBrick() *BrickRef {
	if x != nil {
		return x.Brick
	}
	return nil
}

type RendererPrincipalView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebContentsId int32                  `protobuf:"varint,1,opt,name=web_contents_id,json=webContentsId,proto3" json:"web_contents_id,omitempty"`
	BindingId     string                 `protobuf:"bytes,2,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	Brick         *BrickRef              `protobuf:"bytes,3,opt,name=brick,proto3" json:"brick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RendererPrincipalView) Reset() {
	*x = RendererPrincipalView{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RendererPrincipalView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RendererPrincipalView) ProtoMessage() {}

func (x *RendererPrincipalView) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RendererPrincipalView.ProtoReflect.Descriptor instead.
func (*RendererPrincipalView) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *RendererPrincipalView) GetWebContentsId() int32 {
	if x != nil {
		return x.WebContentsId
	}
	return 0
}

func (x *RendererPrincipalView) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *RendererPrincipalView) GetBrick() *BrickRef {
	if x != nil {
		return x.Brick
	}
	return nil
}

type HostPrincipalView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subsystem     string                 `protobuf:"bytes,1,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostPrincipalView) Reset() {
	*x = HostPrincipalView{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostPrincipalView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPrincipalView) ProtoMessage() {}

func (x *HostPrincipalView) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPrincipalView.ProtoReflect.Descriptor instead.
func (*HostPrincipalView) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *HostPrincipalView) GetSubsystem() string {
	if x != nil {
		return x.Subsystem
	}
	return ""
}

// PrincipalView 仅供 SDK 展示。授权必须从连接上下文解析，忽略 payload 自报身份。
type PrincipalView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Principal:
	//
	//	*PrincipalView_Runtime
	//	*PrincipalView_Renderer
	//	*PrincipalView_Host
	Principal     isPrincipalView_Principal `protobuf_oneof:"principal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalView) Reset() {
	*x = PrincipalView{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalView) ProtoMessage() {}

func (x *PrincipalView) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalView.ProtoReflect.Descriptor instead.
func (*PrincipalView) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *PrincipalView) GetPrincipal() isPrincipalView_Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *PrincipalView) GetRuntime() *RuntimePrincipalView {
	if x != nil {
		if x, ok := x.Principal.(*PrincipalView_Runtime); ok {
			return x.Runtime
		}
	}
	return nil
}

func (x *PrincipalView) GetRenderer() *RendererPrincipalView {
	if x != nil {
		if x, ok := x.Principal.(*PrincipalView_Renderer); ok {
			return x.Renderer
		}
	}
	return nil
}

func (x *PrincipalView) GetHost() *HostPrincipalView {
	if x != nil {
		if x, ok := x.Principal.(*PrincipalView_Host); ok {
			return x.Host
		}
	}
	return nil
}

type isPrincipalView_Principal interface {
	isPrincipalView_Principal()
}

type PrincipalView_Runtime struct {
	Runtime *RuntimePrincipalView `protobuf:"bytes,1,opt,name=runtime,proto3,oneof"`
}

type PrincipalView_Renderer struct {
	Renderer *RendererPrincipalView `protobuf:"bytes,2,opt,name=renderer,proto3,oneof"`
}

type PrincipalView_Host struct {
	Host *HostPrincipalView `protobuf:"bytes,3,opt,name=host,proto3,oneof"`
}

func (*PrincipalView_Runtime) isPrincipalView_Principal() {}

func (*PrincipalView_Renderer) isPrincipalView_Principal() {}

func (*PrincipalView_Host) isPrincipalView_Principal() {}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x12brickly.runtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\bBrickRef\x12\x19\n" +
	"\bbrick_id\x18\x01 \x01(\tR\abrickId\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xf5\x01\n" +
	"\vResourceRef\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\"\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tH\x00R\tmediaType\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\fR\x06sha256\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB\r\n" +
	"\v_media_typeB\a\n" +
	"\x05_name\"\v\n" +
	"\tNullValue\"A\n" +
	"\tBrickList\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.brickly.runtime.v1.BrickValueR\x05items\"Z\n" +
	"\x10BrickObjectField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05value\"K\n" +
	"\vBrickObject\x12<\n" +
	"\x06fields\x18\x01 \x03(\v2$.brickly.runtime.v1.BrickObjectFieldR\x06fields\"\xe3\x03\n" +
	"\n" +
	"BrickValue\x12>\n" +
	"\n" +
	"null_value\x18\x01 \x01(\v2\x1d.brickly.runtime.v1.NullValueH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12.\n" +
	"\x12safe_integer_value\x18\x03 \x01(\x12H\x00R\x10safeIntegerValue\x12#\n" +
	"\fnumber_value\x18\x04 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x06 \x01(\fH\x00R\n" +
	"bytesValue\x12>\n" +
	"\n" +
	"list_value\x18\a \x01(\v2\x1d.brickly.runtime.v1.BrickListH\x00R\tlistValue\x12D\n" +
	"\fobject_value\x18\b \x01(\v2\x1f.brickly.runtime.v1.BrickObjectH\x00R\vobjectValue\x12H\n" +
	"\x0eresource_value\x18\t \x01(\v2\x1f.brickly.runtime.v1.ResourceRefH\x00R\rresourceValueB\a\n" +
	"\x05value\"g\n" +
	"\fTraceContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12)\n" +
	"\x0eparent_span_id\x18\x02 \x01(\tH\x00R\fparentSpanId\x88\x01\x01B\x11\n" +
	"\x0f_parent_span_id\"v\n" +
	"\x14RuntimePrincipalView\x12*\n" +
	"\x11runtime_handle_id\x18\x01 \x01(\tR\x0fruntimeHandleId\x122\n" +
	"\x05brick\x18\x02 \x01(\v2\x1c.brickly.runtime.v1.BrickRefR\x05brick\"\x92\x01\n" +
	"\x15RendererPrincipalView\x12&\n" +
	"\x0fweb_contents_id\x18\x01 \x01(\x05R\rwebContentsId\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x02 \x01(\tR\tbindingId\x122\n" +
	"\x05brick\x18\x03 \x01(\v2\x1c.brickly.runtime.v1.BrickRefR\x05brick\"1\n" +
	"\x11HostPrincipalView\x12\x1c\n" +
	"\tsubsystem\x18\x01 \x01(\tR\tsubsystem\"\xe8\x01\n" +
	"\rPrincipalView\x12D\n" +
	"\aruntime\x18\x01 \x01(\v2(.brickly.runtime.v1.RuntimePrincipalViewH\x00R\aruntime\x12G\n" +
	"\brenderer\x18\x02 \x01(\v2).brickly.runtime.v1.RendererPrincipalViewH\x00R\brenderer\x12;\n" +
	"\x04host\x18\x03 \x01(\v2%.brickly.runtime.v1.HostPrincipalViewH\x00R\x04hostB\v\n" +
	"\tprincipalB\xc2\x01\n" +
	"\x16com.brickly.runtime.v1B\vCommonProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_common_proto_goTypes = []any{
	(*BrickRef)(nil),              // 0: brickly.runtime.v1.BrickRef
	(*ResourceRef)(nil),           // 1: brickly.runtime.v1.ResourceRef
	(*NullValue)(nil),             // 2: brickly.runtime.v1.NullValue
	(*BrickList)(nil),             // 3: brickly.runtime.v1.BrickList
	(*BrickObjectField)(nil),      // 4: brickly.runtime.v1.BrickObjectField
	(*BrickObject)(nil),           // 5: brickly.runtime.v1.BrickObject
	(*BrickValue)(nil),            // 6: brickly.runtime.v1.BrickValue
	(*TraceContext)(nil),          // 7: brickly.runtime.v1.TraceContext
	(*RuntimePrincipalView)(nil),  // 8: brickly.runtime.v1.RuntimePrincipalView
	(*RendererPrincipalView)(nil), // 9: brickly.runtime.v1.RendererPrincipalView
	(*HostPrincipalView)(nil),     // 10: brickly.runtime.v1.HostPrincipalView
	(*PrincipalView)(nil),         // 11: brickly.runtime.v1.PrincipalView
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	12, // 0: brickly.runtime.v1.ResourceRef.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 1: brickly.runtime.v1.BrickList.items:type_name -> brickly.runtime.v1.BrickValue
	6,  // 2: brickly.runtime.v1.BrickObjectField.value:type_name -> brickly.runtime.v1.BrickValue
	4,  // 3: brickly.runtime.v1.BrickObject.fields:type_name -> brickly.runtime.v1.BrickObjectField
	2,  // 4: brickly.runtime.v1.BrickValue.null_value:type_name -> brickly.runtime.v1.NullValue
	3,  // 5: brickly.runtime.v1.BrickValue.list_value:type_name -> brickly.runtime.v1.BrickList
	5,  // 6: brickly.runtime.v1.BrickValue.object_value:type_name -> brickly.runtime.v1.BrickObject
	1,  // 7: brickly.runtime.v1.BrickValue.resource_value:type_name -> brickly.runtime.v1.ResourceRef
	0,  // 8: brickly.runtime.v1.RuntimePrincipalView.brick:type_name -> brickly.runtime.v1.BrickRef
	0,  // 9: brickly.runtime.v1.RendererPrincipalView.brick:type_name -> brickly.runtime.v1.BrickRef
	8,  // 10: brickly.runtime.v1.PrincipalView.runtime:type_name -> brickly.runtime.v1.RuntimePrincipalView
	9,  // 11: brickly.runtime.v1.PrincipalView.renderer:type_name -> brickly.runtime.v1.RendererPrincipalView
	10, // 12: brickly.runtime.v1.PrincipalView.host:type_name -> brickly.runtime.v1.HostPrincipalView
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_proto_msgTypes[6].OneofWrappers = []any{
		(*BrickValue_NullValue)(nil),
		(*BrickValue_BoolValue)(nil),
		(*BrickValue_SafeIntegerValue)(nil),
		(*BrickValue_NumberValue)(nil),
		(*BrickValue_StringValue)(nil),
		(*BrickValue_BytesValue)(nil),
		(*BrickValue_ListValue)(nil),
		(*BrickValue_ObjectValue)(nil),
		(*BrickValue_ResourceValue)(nil),
	}
	file_common_proto_msgTypes[7].OneofWrappers = []any{}
	file_common_proto_msgTypes[11].OneofWrappers = []any{
		(*PrincipalView_Runtime)(nil),
		(*PrincipalView_Renderer)(nil),
		(*PrincipalView_Host)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
