// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: command.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrickCommandService_Invoke_FullMethodName   = "/brickly.runtime.v1.BrickCommandService/Invoke"
	BrickCommandService_Interact_FullMethodName = "/brickly.runtime.v1.BrickCommandService/Interact"
)

// BrickCommandServiceClient is the client API for BrickCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrickCommandService 由 Runtime 提供，Host 通过 RuntimeHandle 上的长期 channel 调用。
// 可信 principal、invocationId、deadline 和 Trace 由 Host 放入 gRPC metadata。
type BrickCommandServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResult, error)
	Interact(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type brickCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrickCommandServiceClient(cc grpc.ClientConnInterface) BrickCommandServiceClient {
	return &brickCommandServiceClient{cc}
}

func (c *brickCommandServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResult)
	err := c.cc.Invoke(ctx, BrickCommandService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brickCommandServiceClient) Interact(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrickCommandService_ServiceDesc.Streams[0], BrickCommandService_Interact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrickCommandService_InteractClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// BrickCommandServiceServer is the server API for BrickCommandService service.
// All implementations must embed UnimplementedBrickCommandServiceServer
// for forward compatibility.
//
// BrickCommandService 由 Runtime 提供，Host 通过 RuntimeHandle 上的长期 channel 调用。
// 可信 principal、invocationId、deadline 和 Trace 由 Host 放入 gRPC metadata。
type BrickCommandServiceServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResult, error)
	Interact(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedBrickCommandServiceServer()
}

// UnimplementedBrickCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrickCommandServiceServer struct{}

func (UnimplementedBrickCommandServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedBrickCommandServiceServer) Interact(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Interact not implemented")
}
func (UnimplementedBrickCommandServiceServer) mustEmbedUnimplementedBrickCommandServiceServer() {}
func (UnimplementedBrickCommandServiceServer) testEmbeddedByValue()                             {}

// UnsafeBrickCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrickCommandServiceServer will
// result in compilation errors.
type UnsafeBrickCommandServiceServer interface {
	mustEmbedUnimplementedBrickCommandServiceServer()
}

func RegisterBrickCommandServiceServer(s grpc.ServiceRegistrar, srv BrickCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrickCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrickCommandService_ServiceDesc, srv)
}

func _BrickCommandService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrickCommandServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrickCommandService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrickCommandServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrickCommandService_Interact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrickCommandServiceServer).Interact(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrickCommandService_InteractServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// BrickCommandService_ServiceDesc is the grpc.ServiceDesc for BrickCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrickCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brickly.runtime.v1.BrickCommandService",
	HandlerType: (*BrickCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _BrickCommandService_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Interact",
			Handler:       _BrickCommandService_Interact_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "command.proto",
}
