// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: connector.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectorInvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrickId       string                 `protobuf:"bytes,1,opt,name=brick_id,json=brickId,proto3" json:"brick_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Input         *BrickValue            `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorInvokeRequest) Reset() {
	*x = ConnectorInvokeRequest{}
	mi := &file_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorInvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorInvokeRequest) ProtoMessage() {}

func (x *ConnectorInvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorInvokeRequest.ProtoReflect.Descriptor instead.
func (*ConnectorInvokeRequest) Descriptor() ([]byte, []int) {
	return file_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorInvokeRequest) GetBrickId() string {
	if x != nil {
		return x.BrickId
	}
	return ""
}

func (x *ConnectorInvokeRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ConnectorInvokeRequest) GetInput() *BrickValue {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_connector_proto protoreflect.FileDescriptor

const file_connector_proto_rawDesc = "" +
	"\n" +
	"\x0fconnector.proto\x12\x12brickly.runtime.v1\x1a\rcommand.proto\x1a\fcommon.proto\"\x88\x01\n" +
	"\x16ConnectorInvokeRequest\x12\x19\n" +
	"\bbrick_id\x18\x01 \x01(\tR\abrickId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x124\n" +
	"\x05input\x18\x03 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05input2\xc1\x01\n" +
	"\x15BrickConnectorService\x12V\n" +
	"\x06Invoke\x12*.brickly.runtime.v1.ConnectorInvokeRequest\x1a .brickly.runtime.v1.InvokeResult\x12P\n" +
	"\bInteract\x12\x1f.brickly.runtime.v1.ClientFrame\x1a\x1f.brickly.runtime.v1.ServerFrame(\x010\x01B\xc5\x01\n" +
	"\x16com.brickly.runtime.v1B\x0eConnectorProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_connector_proto_rawDescOnce sync.Once
	file_connector_proto_rawDescData []byte
)

func file_connector_proto_rawDescGZIP() []byte {
	file_connector_proto_rawDescOnce.Do(func() {
		file_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connector_proto_rawDesc), len(file_connector_proto_rawDesc)))
	})
	return file_connector_proto_rawDescData
}

var file_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connector_proto_goTypes = []any{
	(*ConnectorInvokeRequest)(nil), // 0: brickly.runtime.v1.ConnectorInvokeRequest
	(*BrickValue)(nil),             // 1: brickly.runtime.v1.BrickValue
	(*ClientFrame)(nil),            // 2: brickly.runtime.v1.ClientFrame
	(*InvokeResult)(nil),           // 3: brickly.runtime.v1.InvokeResult
	(*ServerFrame)(nil),            // 4: brickly.runtime.v1.ServerFrame
}
var file_connector_proto_depIdxs = []int32{
	1, // 0: brickly.runtime.v1.ConnectorInvokeRequest.input:type_name -> brickly.runtime.v1.BrickValue
	0, // 1: brickly.runtime.v1.BrickConnectorService.Invoke:input_type -> brickly.runtime.v1.ConnectorInvokeRequest
	2, // 2: brickly.runtime.v1.BrickConnectorService.Interact:input_type -> brickly.runtime.v1.ClientFrame
	3, // 3: brickly.runtime.v1.BrickConnectorService.Invoke:output_type -> brickly.runtime.v1.InvokeResult
	4, // 4: brickly.runtime.v1.BrickConnectorService.Interact:output_type -> brickly.runtime.v1.ServerFrame
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connector_proto_init() }
func file_connector_proto_init() {
	if File_connector_proto != nil {
		return
	}
	file_command_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connector_proto_rawDesc), len(file_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connector_proto_goTypes,
		DependencyIndexes: file_connector_proto_depIdxs,
		MessageInfos:      file_connector_proto_msgTypes,
	}.Build()
	File_connector_proto = out.File
	file_connector_proto_goTypes = nil
	file_connector_proto_depIdxs = nil
}
