// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: error.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BrickError 放入非 OK gRPC status details。
// message 面向开发者但必须脱敏。
// details 只能是本文件登记的 detail message，不得放入任意对象、路径、密钥或资源内容。
//
// 稳定 code 与 gRPC status 映射：
//
//	INVALID_INPUT               -> INVALID_ARGUMENT
//	ACCESS_DENIED               -> PERMISSION_DENIED
//	NOT_FOUND                   -> NOT_FOUND
//	CONFLICT                    -> ABORTED
//	LIMIT_EXCEEDED              -> RESOURCE_EXHAUSTED
//	DEADLINE_EXCEEDED           -> DEADLINE_EXCEEDED
//	CANCELLED                   -> CANCELLED
//	OUTCOME_UNKNOWN             -> UNAVAILABLE
//	CALL_CYCLE_DETECTED         -> FAILED_PRECONDITION
//	REQUEST_HANDLER_UNAVAILABLE -> FAILED_PRECONDITION
//	PROTOCOL_VIOLATION          -> INTERNAL
//	INTERNAL                    -> INTERNAL
//	INVALID_RESOURCE_REF        -> INVALID_ARGUMENT
//	RESOURCE_NOT_FOUND          -> NOT_FOUND
//	RESOURCE_ACCESS_DENIED      -> PERMISSION_DENIED
//	RESOURCE_EXPIRED            -> FAILED_PRECONDITION
//	RESOURCE_REVOKED            -> FAILED_PRECONDITION
//	RESOURCE_QUOTA_EXCEEDED     -> RESOURCE_EXHAUSTED
//	RESOURCE_OFFSET_MISMATCH    -> INVALID_ARGUMENT
//	RESOURCE_INTEGRITY_FAILED   -> DATA_LOSS
type BrickError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       *anypb.Any             `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrickError) Reset() {
	*x = BrickError{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrickError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrickError) ProtoMessage() {}

func (x *BrickError) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrickError.ProtoReflect.Descriptor instead.
func (*BrickError) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *BrickError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BrickError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BrickError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *BrickError) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type InvalidInputDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidInputDetail) Reset() {
	*x = InvalidInputDetail{}
	mi := &file_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidInputDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidInputDetail) ProtoMessage() {}

func (x *InvalidInputDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidInputDetail.ProtoReflect.Descriptor instead.
func (*InvalidInputDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidInputDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *InvalidInputDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AccessDeniedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessDeniedDetail) Reset() {
	*x = AccessDeniedDetail{}
	mi := &file_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessDeniedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDeniedDetail) ProtoMessage() {}

func (x *AccessDeniedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDeniedDetail.ProtoReflect.Descriptor instead.
func (*AccessDeniedDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{2}
}

func (x *AccessDeniedDetail) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type NotFoundDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceKind  string                 `protobuf:"bytes,1,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFoundDetail) Reset() {
	*x = NotFoundDetail{}
	mi := &file_error_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFoundDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFoundDetail) ProtoMessage() {}

func (x *NotFoundDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFoundDetail.ProtoReflect.Descriptor instead.
func (*NotFoundDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{3}
}

func (x *NotFoundDetail) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

type ConflictDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictDetail) Reset() {
	*x = ConflictDetail{}
	mi := &file_error_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictDetail) ProtoMessage() {}

func (x *ConflictDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictDetail.ProtoReflect.Descriptor instead.
func (*ConflictDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{4}
}

func (x *ConflictDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LimitExceededDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimension     string                 `protobuf:"bytes,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Observed      int64                  `protobuf:"varint,3,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitExceededDetail) Reset() {
	*x = LimitExceededDetail{}
	mi := &file_error_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitExceededDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitExceededDetail) ProtoMessage() {}

func (x *LimitExceededDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitExceededDetail.ProtoReflect.Descriptor instead.
func (*LimitExceededDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{5}
}

func (x *LimitExceededDetail) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *LimitExceededDetail) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LimitExceededDetail) GetObserved() int64 {
	if x != nil {
		return x.Observed
	}
	return 0
}

type DeadlineExceededDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeadlineUnixMs int64                  `protobuf:"varint,1,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeadlineExceededDetail) Reset() {
	*x = DeadlineExceededDetail{}
	mi := &file_error_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadlineExceededDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadlineExceededDetail) ProtoMessage() {}

func (x *DeadlineExceededDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadlineExceededDetail.ProtoReflect.Descriptor instead.
func (*DeadlineExceededDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{6}
}

func (x *DeadlineExceededDetail) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type CancelledDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelledDetail) Reset() {
	*x = CancelledDetail{}
	mi := &file_error_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelledDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelledDetail) ProtoMessage() {}

func (x *CancelledDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelledDetail.ProtoReflect.Descriptor instead.
func (*CancelledDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{7}
}

func (x *CancelledDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OutcomeUnknownDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutcomeUnknownDetail) Reset() {
	*x = OutcomeUnknownDetail{}
	mi := &file_error_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutcomeUnknownDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeUnknownDetail) ProtoMessage() {}

func (x *OutcomeUnknownDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeUnknownDetail.ProtoReflect.Descriptor instead.
func (*OutcomeUnknownDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{8}
}

func (x *OutcomeUnknownDetail) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type CallCycleDetectedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         uint32                 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCycleDetectedDetail) Reset() {
	*x = CallCycleDetectedDetail{}
	mi := &file_error_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCycleDetectedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCycleDetectedDetail) ProtoMessage() {}

func (x *CallCycleDetectedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCycleDetectedDetail.ProtoReflect.Descriptor instead.
func (*CallCycleDetectedDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{9}
}

func (x *CallCycleDetectedDetail) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type RequestHandlerUnavailableDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHandlerUnavailableDetail) Reset() {
	*x = RequestHandlerUnavailableDetail{}
	mi := &file_error_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHandlerUnavailableDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHandlerUnavailableDetail) ProtoMessage() {}

func (x *RequestHandlerUnavailableDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHandlerUnavailableDetail.ProtoReflect.Descriptor instead.
func (*RequestHandlerUnavailableDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{10}
}

func (x *RequestHandlerUnavailableDetail) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ProtocolViolationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolViolationDetail) Reset() {
	*x = ProtocolViolationDetail{}
	mi := &file_error_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolViolationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolViolationDetail) ProtoMessage() {}

func (x *ProtocolViolationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolViolationDetail.ProtoReflect.Descriptor instead.
func (*ProtocolViolationDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{11}
}

func (x *ProtocolViolationDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InternalDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorId       string                 `protobuf:"bytes,1,opt,name=error_id,json=errorId,proto3" json:"error_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalDetail) Reset() {
	*x = InternalDetail{}
	mi := &file_error_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalDetail) ProtoMessage() {}

func (x *InternalDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalDetail.ProtoReflect.Descriptor instead.
func (*InternalDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{12}
}

func (x *InternalDetail) GetErrorId() string {
	if x != nil {
		return x.ErrorId
	}
	return ""
}

type InvalidResourceRefDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceIdPrefix string                 `protobuf:"bytes,1,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvalidResourceRefDetail) Reset() {
	*x = InvalidResourceRefDetail{}
	mi := &file_error_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidResourceRefDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidResourceRefDetail) ProtoMessage() {}

func (x *InvalidResourceRefDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidResourceRefDetail.ProtoReflect.Descriptor instead.
func (*InvalidResourceRefDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{13}
}

func (x *InvalidResourceRefDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

func (x *InvalidResourceRefDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResourceNotFoundDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceIdPrefix string                 `protobuf:"bytes,1,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceNotFoundDetail) Reset() {
	*x = ResourceNotFoundDetail{}
	mi := &file_error_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceNotFoundDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceNotFoundDetail) ProtoMessage() {}

func (x *ResourceNotFoundDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceNotFoundDetail.ProtoReflect.Descriptor instead.
func (*ResourceNotFoundDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceNotFoundDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

type ResourceAccessDeniedDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceIdPrefix string                 `protobuf:"bytes,1,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceAccessDeniedDetail) Reset() {
	*x = ResourceAccessDeniedDetail{}
	mi := &file_error_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAccessDeniedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAccessDeniedDetail) ProtoMessage() {}

func (x *ResourceAccessDeniedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAccessDeniedDetail.ProtoReflect.Descriptor instead.
func (*ResourceAccessDeniedDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceAccessDeniedDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

type ResourceExpiredDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceIdPrefix string                 `protobuf:"bytes,1,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceExpiredDetail) Reset() {
	*x = ResourceExpiredDetail{}
	mi := &file_error_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceExpiredDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceExpiredDetail) ProtoMessage() {}

func (x *ResourceExpiredDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceExpiredDetail.ProtoReflect.Descriptor instead.
func (*ResourceExpiredDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceExpiredDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

type ResourceRevokedDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceIdPrefix string                 `protobuf:"bytes,1,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceRevokedDetail) Reset() {
	*x = ResourceRevokedDetail{}
	mi := &file_error_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRevokedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRevokedDetail) ProtoMessage() {}

func (x *ResourceRevokedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRevokedDetail.ProtoReflect.Descriptor instead.
func (*ResourceRevokedDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{17}
}

func (x *ResourceRevokedDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

type ResourceQuotaExceededDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Dimension        string                 `protobuf:"bytes,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Limit            int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Observed         int64                  `protobuf:"varint,3,opt,name=observed,proto3" json:"observed,omitempty"`
	ResourceIdPrefix string                 `protobuf:"bytes,4,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceQuotaExceededDetail) Reset() {
	*x = ResourceQuotaExceededDetail{}
	mi := &file_error_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQuotaExceededDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQuotaExceededDetail) ProtoMessage() {}

func (x *ResourceQuotaExceededDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQuotaExceededDetail.ProtoReflect.Descriptor instead.
func (*ResourceQuotaExceededDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{18}
}

func (x *ResourceQuotaExceededDetail) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *ResourceQuotaExceededDetail) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResourceQuotaExceededDetail) GetObserved() int64 {
	if x != nil {
		return x.Observed
	}
	return 0
}

func (x *ResourceQuotaExceededDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

type ResourceOffsetMismatchDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedOffset uint64                 `protobuf:"varint,1,opt,name=expected_offset,json=expectedOffset,proto3" json:"expected_offset,omitempty"`
	ObservedOffset uint64                 `protobuf:"varint,2,opt,name=observed_offset,json=observedOffset,proto3" json:"observed_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceOffsetMismatchDetail) Reset() {
	*x = ResourceOffsetMismatchDetail{}
	mi := &file_error_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceOffsetMismatchDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceOffsetMismatchDetail) ProtoMessage() {}

func (x *ResourceOffsetMismatchDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceOffsetMismatchDetail.ProtoReflect.Descriptor instead.
func (*ResourceOffsetMismatchDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{19}
}

func (x *ResourceOffsetMismatchDetail) GetExpectedOffset() uint64 {
	if x != nil {
		return x.ExpectedOffset
	}
	return 0
}

func (x *ResourceOffsetMismatchDetail) GetObservedOffset() uint64 {
	if x != nil {
		return x.ObservedOffset
	}
	return 0
}

type ResourceIntegrityFailedDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceIdPrefix string                 `protobuf:"bytes,1,opt,name=resource_id_prefix,json=resourceIdPrefix,proto3" json:"resource_id_prefix,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceIntegrityFailedDetail) Reset() {
	*x = ResourceIntegrityFailedDetail{}
	mi := &file_error_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceIntegrityFailedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIntegrityFailedDetail) ProtoMessage() {}

func (x *ResourceIntegrityFailedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIntegrityFailedDetail.ProtoReflect.Descriptor instead.
func (*ResourceIntegrityFailedDetail) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceIntegrityFailedDetail) GetResourceIdPrefix() string {
	if x != nil {
		return x.ResourceIdPrefix
	}
	return ""
}

func (x *ResourceIntegrityFailedDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\x12brickly.runtime.v1\x1a\x19google/protobuf/any.proto\"\x88\x01\n" +
	"\n" +
	"BrickError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12.\n" +
	"\adetails\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\adetails\"B\n" +
	"\x12InvalidInputDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"4\n" +
	"\x12AccessDeniedDetail\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"5\n" +
	"\x0eNotFoundDetail\x12#\n" +
	"\rresource_kind\x18\x01 \x01(\tR\fresourceKind\"(\n" +
	"\x0eConflictDetail\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"e\n" +
	"\x13LimitExceededDetail\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\tR\tdimension\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\x03R\bobserved\"B\n" +
	"\x16DeadlineExceededDetail\x12(\n" +
	"\x10deadline_unix_ms\x18\x01 \x01(\x03R\x0edeadlineUnixMs\")\n" +
	"\x0fCancelledDetail\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"4\n" +
	"\x14OutcomeUnknownDetail\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\"/\n" +
	"\x17CallCycleDetectedDetail\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\rR\x05depth\"@\n" +
	"\x1fRequestHandlerUnavailableDetail\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"1\n" +
	"\x17ProtocolViolationDetail\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"+\n" +
	"\x0eInternalDetail\x12\x19\n" +
	"\berror_id\x18\x01 \x01(\tR\aerrorId\"`\n" +
	"\x18InvalidResourceRefDetail\x12,\n" +
	"\x12resource_id_prefix\x18\x01 \x01(\tR\x10resourceIdPrefix\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"F\n" +
	"\x16ResourceNotFoundDetail\x12,\n" +
	"\x12resource_id_prefix\x18\x01 \x01(\tR\x10resourceIdPrefix\"J\n" +
	"\x1aResourceAccessDeniedDetail\x12,\n" +
	"\x12resource_id_prefix\x18\x01 \x01(\tR\x10resourceIdPrefix\"E\n" +
	"\x15ResourceExpiredDetail\x12,\n" +
	"\x12resource_id_prefix\x18\x01 \x01(\tR\x10resourceIdPrefix\"E\n" +
	"\x15ResourceRevokedDetail\x12,\n" +
	"\x12resource_id_prefix\x18\x01 \x01(\tR\x10resourceIdPrefix\"\x9b\x01\n" +
	"\x1bResourceQuotaExceededDetail\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\tR\tdimension\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\x03R\bobserved\x12,\n" +
	"\x12resource_id_prefix\x18\x04 \x01(\tR\x10resourceIdPrefix\"p\n" +
	"\x1cResourceOffsetMismatchDetail\x12'\n" +
	"\x0fexpected_offset\x18\x01 \x01(\x04R\x0eexpectedOffset\x12'\n" +
	"\x0fobserved_offset\x18\x02 \x01(\x04R\x0eobservedOffset\"e\n" +
	"\x1dResourceIntegrityFailedDetail\x12,\n" +
	"\x12resource_id_prefix\x18\x01 \x01(\tR\x10resourceIdPrefix\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB\xc1\x01\n" +
	"\x16com.brickly.runtime.v1B\n" +
	"ErrorProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_error_proto_goTypes = []any{
	(*BrickError)(nil),                      // 0: brickly.runtime.v1.BrickError
	(*InvalidInputDetail)(nil),              // 1: brickly.runtime.v1.InvalidInputDetail
	(*AccessDeniedDetail)(nil),              // 2: brickly.runtime.v1.AccessDeniedDetail
	(*NotFoundDetail)(nil),                  // 3: brickly.runtime.v1.NotFoundDetail
	(*ConflictDetail)(nil),                  // 4: brickly.runtime.v1.ConflictDetail
	(*LimitExceededDetail)(nil),             // 5: brickly.runtime.v1.LimitExceededDetail
	(*DeadlineExceededDetail)(nil),          // 6: brickly.runtime.v1.DeadlineExceededDetail
	(*CancelledDetail)(nil),                 // 7: brickly.runtime.v1.CancelledDetail
	(*OutcomeUnknownDetail)(nil),            // 8: brickly.runtime.v1.OutcomeUnknownDetail
	(*CallCycleDetectedDetail)(nil),         // 9: brickly.runtime.v1.CallCycleDetectedDetail
	(*RequestHandlerUnavailableDetail)(nil), // 10: brickly.runtime.v1.RequestHandlerUnavailableDetail
	(*ProtocolViolationDetail)(nil),         // 11: brickly.runtime.v1.ProtocolViolationDetail
	(*InternalDetail)(nil),                  // 12: brickly.runtime.v1.InternalDetail
	(*InvalidResourceRefDetail)(nil),        // 13: brickly.runtime.v1.InvalidResourceRefDetail
	(*ResourceNotFoundDetail)(nil),          // 14: brickly.runtime.v1.ResourceNotFoundDetail
	(*ResourceAccessDeniedDetail)(nil),      // 15: brickly.runtime.v1.ResourceAccessDeniedDetail
	(*ResourceExpiredDetail)(nil),           // 16: brickly.runtime.v1.ResourceExpiredDetail
	(*ResourceRevokedDetail)(nil),           // 17: brickly.runtime.v1.ResourceRevokedDetail
	(*ResourceQuotaExceededDetail)(nil),     // 18: brickly.runtime.v1.ResourceQuotaExceededDetail
	(*ResourceOffsetMismatchDetail)(nil),    // 19: brickly.runtime.v1.ResourceOffsetMismatchDetail
	(*ResourceIntegrityFailedDetail)(nil),   // 20: brickly.runtime.v1.ResourceIntegrityFailedDetail
	(*anypb.Any)(nil),                       // 21: google.protobuf.Any
}
var file_error_proto_depIdxs = []int32{
	21, // 0: brickly.runtime.v1.BrickError.details:type_name -> google.protobuf.Any
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
