// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       *BrickValue            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *PublishEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishEventRequest) GetPayload() *BrickValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeEventsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type DomainEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       *BrickValue            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEvent) Reset() {
	*x = DomainEvent{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEvent) ProtoMessage() {}

func (x *DomainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEvent.ProtoReflect.Descriptor instead.
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *DomainEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DomainEvent) GetPayload() *BrickValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x12brickly.runtime.v1\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"e\n" +
	"\x13PublishEventRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\apayload\".\n" +
	"\x16SubscribeEventsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"]\n" +
	"\vDomainEvent\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\apayload2\xb6\x01\n" +
	"\fEventService\x12J\n" +
	"\aPublish\x12'.brickly.runtime.v1.PublishEventRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\tSubscribe\x12*.brickly.runtime.v1.SubscribeEventsRequest\x1a\x1f.brickly.runtime.v1.DomainEvent0\x01B\xc1\x01\n" +
	"\x16com.brickly.runtime.v1B\n" +
	"EventProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_event_proto_goTypes = []any{
	(*PublishEventRequest)(nil),    // 0: brickly.runtime.v1.PublishEventRequest
	(*SubscribeEventsRequest)(nil), // 1: brickly.runtime.v1.SubscribeEventsRequest
	(*DomainEvent)(nil),            // 2: brickly.runtime.v1.DomainEvent
	(*BrickValue)(nil),             // 3: brickly.runtime.v1.BrickValue
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_event_proto_depIdxs = []int32{
	3, // 0: brickly.runtime.v1.PublishEventRequest.payload:type_name -> brickly.runtime.v1.BrickValue
	3, // 1: brickly.runtime.v1.DomainEvent.payload:type_name -> brickly.runtime.v1.BrickValue
	0, // 2: brickly.runtime.v1.EventService.Publish:input_type -> brickly.runtime.v1.PublishEventRequest
	1, // 3: brickly.runtime.v1.EventService.Subscribe:input_type -> brickly.runtime.v1.SubscribeEventsRequest
	4, // 4: brickly.runtime.v1.EventService.Publish:output_type -> google.protobuf.Empty
	2, // 5: brickly.runtime.v1.EventService.Subscribe:output_type -> brickly.runtime.v1.DomainEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
