// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// screenshot.selectRegion / screen.getPrimaryDisplay / clipboard.readContent / system.getPath
	Method        string      `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Input         *BrickValue `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformCallRequest) Reset() {
	*x = PlatformCallRequest{}
	mi := &file_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformCallRequest) ProtoMessage() {}

func (x *PlatformCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformCallRequest.ProtoReflect.Descriptor instead.
func (*PlatformCallRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformCallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PlatformCallRequest) GetInput() *BrickValue {
	if x != nil {
		return x.Input
	}
	return nil
}

type PlatformCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *BrickValue            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformCallResponse) Reset() {
	*x = PlatformCallResponse{}
	mi := &file_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformCallResponse) ProtoMessage() {}

func (x *PlatformCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformCallResponse.ProtoReflect.Descriptor instead.
func (*PlatformCallResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformCallResponse) GetResult() *BrickValue {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_platform_proto protoreflect.FileDescriptor

const file_platform_proto_rawDesc = "" +
	"\n" +
	"\x0eplatform.proto\x12\x12brickly.runtime.v1\x1a\fcommon.proto\"c\n" +
	"\x13PlatformCallRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x124\n" +
	"\x05input\x18\x02 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05input\"N\n" +
	"\x14PlatformCallResponse\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x06result2l\n" +
	"\x0fPlatformService\x12Y\n" +
	"\x04Call\x12'.brickly.runtime.v1.PlatformCallRequest\x1a(.brickly.runtime.v1.PlatformCallResponseB\xc4\x01\n" +
	"\x16com.brickly.runtime.v1B\rPlatformProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_platform_proto_rawDescOnce sync.Once
	file_platform_proto_rawDescData []byte
)

func file_platform_proto_rawDescGZIP() []byte {
	file_platform_proto_rawDescOnce.Do(func() {
		file_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_proto_rawDesc), len(file_platform_proto_rawDesc)))
	})
	return file_platform_proto_rawDescData
}

var file_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_platform_proto_goTypes = []any{
	(*PlatformCallRequest)(nil),  // 0: brickly.runtime.v1.PlatformCallRequest
	(*PlatformCallResponse)(nil), // 1: brickly.runtime.v1.PlatformCallResponse
	(*BrickValue)(nil),           // 2: brickly.runtime.v1.BrickValue
}
var file_platform_proto_depIdxs = []int32{
	2, // 0: brickly.runtime.v1.PlatformCallRequest.input:type_name -> brickly.runtime.v1.BrickValue
	2, // 1: brickly.runtime.v1.PlatformCallResponse.result:type_name -> brickly.runtime.v1.BrickValue
	0, // 2: brickly.runtime.v1.PlatformService.Call:input_type -> brickly.runtime.v1.PlatformCallRequest
	1, // 3: brickly.runtime.v1.PlatformService.Call:output_type -> brickly.runtime.v1.PlatformCallResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_platform_proto_init() }
func file_platform_proto_init() {
	if File_platform_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_proto_rawDesc), len(file_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_proto_goTypes,
		DependencyIndexes: file_platform_proto_depIdxs,
		MessageInfos:      file_platform_proto_msgTypes,
	}.Build()
	File_platform_proto = out.File
	file_platform_proto_goTypes = nil
	file_platform_proto_depIdxs = nil
}
