// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: registry.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeRegistry_Register_FullMethodName   = "/brickly.runtime.v1.RuntimeRegistry/Register"
	RuntimeRegistry_Unregister_FullMethodName = "/brickly.runtime.v1.RuntimeRegistry/Unregister"
)

// RuntimeRegistryClient is the client API for RuntimeRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeRegistry 由 Host 提供。
// Register 的 bootstrap token 只放在 gRPC metadata，body 不得自报 BrickRef、instanceId 或权限。
// Runtime 必须同时实现标准 grpc.health.v1.Health；Host 用 host-to-runtime token 做健康检查。
// buf:lint:ignore SERVICE_SUFFIX
type RuntimeRegistryClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type runtimeRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeRegistryClient(cc grpc.ClientConnInterface) RuntimeRegistryClient {
	return &runtimeRegistryClient{cc}
}

func (c *runtimeRegistryClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RuntimeRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeRegistryClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RuntimeRegistry_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeRegistryServer is the server API for RuntimeRegistry service.
// All implementations must embed UnimplementedRuntimeRegistryServer
// for forward compatibility.
//
// RuntimeRegistry 由 Host 提供。
// Register 的 bootstrap token 只放在 gRPC metadata，body 不得自报 BrickRef、instanceId 或权限。
// Runtime 必须同时实现标准 grpc.health.v1.Health；Host 用 host-to-runtime token 做健康检查。
// buf:lint:ignore SERVICE_SUFFIX
type RuntimeRegistryServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Unregister(context.Context, *UnregisterRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRuntimeRegistryServer()
}

// UnimplementedRuntimeRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeRegistryServer struct{}

func (UnimplementedRuntimeRegistryServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRuntimeRegistryServer) Unregister(context.Context, *UnregisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedRuntimeRegistryServer) mustEmbedUnimplementedRuntimeRegistryServer() {}
func (UnimplementedRuntimeRegistryServer) testEmbeddedByValue()                         {}

// UnsafeRuntimeRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeRegistryServer will
// result in compilation errors.
type UnsafeRuntimeRegistryServer interface {
	mustEmbedUnimplementedRuntimeRegistryServer()
}

func RegisterRuntimeRegistryServer(s grpc.ServiceRegistrar, srv RuntimeRegistryServer) {
	// If the following call pancis, it indicates UnimplementedRuntimeRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeRegistry_ServiceDesc, srv)
}

func _RuntimeRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeRegistryServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeRegistry_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeRegistryServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeRegistry_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeRegistryServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeRegistry_ServiceDesc is the grpc.ServiceDesc for RuntimeRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brickly.runtime.v1.RuntimeRegistry",
	HandlerType: (*RuntimeRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RuntimeRegistry_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _RuntimeRegistry_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
