// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	FeatureBitset uint64                 `protobuf:"varint,3,opt,name=feature_bitset,json=featureBitset,proto3" json:"feature_bitset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *ProtocolVersion) GetFeatureBitset() uint64 {
	if x != nil {
		return x.FeatureBitset
	}
	return 0
}

type CapabilitySummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Commands         []string               `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	SupportsInteract bool                   `protobuf:"varint,2,opt,name=supports_interact,json=supportsInteract,proto3" json:"supports_interact,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilitySummary) Reset() {
	*x = CapabilitySummary{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitySummary) ProtoMessage() {}

func (x *CapabilitySummary) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitySummary.ProtoReflect.Descriptor instead.
func (*CapabilitySummary) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitySummary) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *CapabilitySummary) GetSupportsInteract() bool {
	if x != nil {
		return x.SupportsInteract
	}
	return false
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime BrickCommandService 的 loopback endpoint，例如 127.0.0.1:port。
	Endpoint      string             `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Protocol      *ProtocolVersion   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Capabilities  *CapabilitySummary `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetProtocol() *ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() *CapabilitySummary {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RuntimeHandleId string                 `protobuf:"bytes,1,opt,name=runtime_handle_id,json=runtimeHandleId,proto3" json:"runtime_handle_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetRuntimeHandleId() string {
	if x != nil {
		return x.RuntimeHandleId
	}
	return ""
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\x12brickly.runtime.v1\x1a\x1bgoogle/protobuf/empty.proto\"d\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12%\n" +
	"\x0efeature_bitset\x18\x03 \x01(\x04R\rfeatureBitset\"\\\n" +
	"\x11CapabilitySummary\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommands\x12+\n" +
	"\x11supports_interact\x18\x02 \x01(\bR\x10supportsInteract\"\xb9\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12?\n" +
	"\bprotocol\x18\x02 \x01(\v2#.brickly.runtime.v1.ProtocolVersionR\bprotocol\x12I\n" +
	"\fcapabilities\x18\x03 \x01(\v2%.brickly.runtime.v1.CapabilitySummaryR\fcapabilities\">\n" +
	"\x10RegisterResponse\x12*\n" +
	"\x11runtime_handle_id\x18\x01 \x01(\tR\x0fruntimeHandleId\"\x13\n" +
	"\x11UnregisterRequest2\xb5\x01\n" +
	"\x0fRuntimeRegistry\x12U\n" +
	"\bRegister\x12#.brickly.runtime.v1.RegisterRequest\x1a$.brickly.runtime.v1.RegisterResponse\x12K\n" +
	"\n" +
	"Unregister\x12%.brickly.runtime.v1.UnregisterRequest\x1a\x16.google.protobuf.EmptyB\xc4\x01\n" +
	"\x16com.brickly.runtime.v1B\rRegistryProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_registry_proto_goTypes = []any{
	(*ProtocolVersion)(nil),   // 0: brickly.runtime.v1.ProtocolVersion
	(*CapabilitySummary)(nil), // 1: brickly.runtime.v1.CapabilitySummary
	(*RegisterRequest)(nil),   // 2: brickly.runtime.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 3: brickly.runtime.v1.RegisterResponse
	(*UnregisterRequest)(nil), // 4: brickly.runtime.v1.UnregisterRequest
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_registry_proto_depIdxs = []int32{
	0, // 0: brickly.runtime.v1.RegisterRequest.protocol:type_name -> brickly.runtime.v1.ProtocolVersion
	1, // 1: brickly.runtime.v1.RegisterRequest.capabilities:type_name -> brickly.runtime.v1.CapabilitySummary
	2, // 2: brickly.runtime.v1.RuntimeRegistry.Register:input_type -> brickly.runtime.v1.RegisterRequest
	4, // 3: brickly.runtime.v1.RuntimeRegistry.Unregister:input_type -> brickly.runtime.v1.UnregisterRequest
	3, // 4: brickly.runtime.v1.RuntimeRegistry.Register:output_type -> brickly.runtime.v1.RegisterResponse
	5, // 5: brickly.runtime.v1.RuntimeRegistry.Unregister:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
