// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resource.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceState int32

const (
	ResourceState_RESOURCE_STATE_UNSPECIFIED ResourceState = 0
	ResourceState_RESOURCE_STATE_AVAILABLE   ResourceState = 1
	ResourceState_RESOURCE_STATE_EXPIRED     ResourceState = 2
	ResourceState_RESOURCE_STATE_REVOKED     ResourceState = 3
)

// Enum value maps for ResourceState.
var (
	ResourceState_name = map[int32]string{
		0: "RESOURCE_STATE_UNSPECIFIED",
		1: "RESOURCE_STATE_AVAILABLE",
		2: "RESOURCE_STATE_EXPIRED",
		3: "RESOURCE_STATE_REVOKED",
	}
	ResourceState_value = map[string]int32{
		"RESOURCE_STATE_UNSPECIFIED": 0,
		"RESOURCE_STATE_AVAILABLE":   1,
		"RESOURCE_STATE_EXPIRED":     2,
		"RESOURCE_STATE_REVOKED":     3,
	}
)

func (x ResourceState) Enum() *ResourceState {
	p := new(ResourceState)
	*p = x
	return p
}

func (x ResourceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceState) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_proto_enumTypes[0].Descriptor()
}

func (ResourceState) Type() protoreflect.EnumType {
	return &file_resource_proto_enumTypes[0]
}

func (x ResourceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceState.Descriptor instead.
func (ResourceState) EnumDescriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

type ResourceStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceStatRequest) Reset() {
	*x = ResourceStatRequest{}
	mi := &file_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatRequest) ProtoMessage() {}

func (x *ResourceStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatRequest.ProtoReflect.Descriptor instead.
func (*ResourceStatRequest) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceStatRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ResourceRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRevokeRequest) Reset() {
	*x = ResourceRevokeRequest{}
	mi := &file_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRevokeRequest) ProtoMessage() {}

func (x *ResourceRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRevokeRequest.ProtoReflect.Descriptor instead.
func (*ResourceRevokeRequest) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRevokeRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ResourceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceRef           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	State         ResourceState          `protobuf:"varint,2,opt,name=state,proto3,enum=brickly.runtime.v1.ResourceState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMetadata) Reset() {
	*x = ResourceMetadata{}
	mi := &file_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetadata) ProtoMessage() {}

func (x *ResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetadata.ProtoReflect.Descriptor instead.
func (*ResourceMetadata) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceMetadata) GetResource() *ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceMetadata) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

type ResourceCreateHeader struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MediaType         *string                `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3,oneof" json:"media_type,omitempty"`
	Name              *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ExpectedSizeBytes *uint64                `protobuf:"varint,3,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3,oneof" json:"expected_size_bytes,omitempty"`
	ExpectedSha256    []byte                 `protobuf:"bytes,4,opt,name=expected_sha256,json=expectedSha256,proto3,oneof" json:"expected_sha256,omitempty"`
	TtlMs             *uint64                `protobuf:"varint,5,opt,name=ttl_ms,json=ttlMs,proto3,oneof" json:"ttl_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceCreateHeader) Reset() {
	*x = ResourceCreateHeader{}
	mi := &file_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCreateHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCreateHeader) ProtoMessage() {}

func (x *ResourceCreateHeader) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCreateHeader.ProtoReflect.Descriptor instead.
func (*ResourceCreateHeader) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceCreateHeader) GetMediaType() string {
	if x != nil && x.MediaType != nil {
		return *x.MediaType
	}
	return ""
}

func (x *ResourceCreateHeader) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ResourceCreateHeader) GetExpectedSizeBytes() uint64 {
	if x != nil && x.ExpectedSizeBytes != nil {
		return *x.ExpectedSizeBytes
	}
	return 0
}

func (x *ResourceCreateHeader) GetExpectedSha256() []byte {
	if x != nil {
		return x.ExpectedSha256
	}
	return nil
}

func (x *ResourceCreateHeader) GetTtlMs() uint64 {
	if x != nil && x.TtlMs != nil {
		return *x.TtlMs
	}
	return 0
}

type ResourceWriteChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceWriteChunk) Reset() {
	*x = ResourceWriteChunk{}
	mi := &file_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWriteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWriteChunk) ProtoMessage() {}

func (x *ResourceWriteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWriteChunk.ProtoReflect.Descriptor instead.
func (*ResourceWriteChunk) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceWriteChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ResourceWriteChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResourceWriteFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ResourceWriteFrame_Header
	//	*ResourceWriteFrame_Chunk
	Body          isResourceWriteFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceWriteFrame) Reset() {
	*x = ResourceWriteFrame{}
	mi := &file_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWriteFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWriteFrame) ProtoMessage() {}

func (x *ResourceWriteFrame) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWriteFrame.ProtoReflect.Descriptor instead.
func (*ResourceWriteFrame) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceWriteFrame) GetBody() isResourceWriteFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResourceWriteFrame) GetHeader() *ResourceCreateHeader {
	if x != nil {
		if x, ok := x.Body.(*ResourceWriteFrame_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ResourceWriteFrame) GetChunk() *ResourceWriteChunk {
	if x != nil {
		if x, ok := x.Body.(*ResourceWriteFrame_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isResourceWriteFrame_Body interface {
	isResourceWriteFrame_Body()
}

type ResourceWriteFrame_Header struct {
	Header *ResourceCreateHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ResourceWriteFrame_Chunk struct {
	Chunk *ResourceWriteChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ResourceWriteFrame_Header) isResourceWriteFrame_Body() {}

func (*ResourceWriteFrame_Chunk) isResourceWriteFrame_Body() {}

type ResourceReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        *uint64                `protobuf:"varint,3,opt,name=length,proto3,oneof" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReadRequest) Reset() {
	*x = ResourceReadRequest{}
	mi := &file_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReadRequest) ProtoMessage() {}

func (x *ResourceReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReadRequest.ProtoReflect.Descriptor instead.
func (*ResourceReadRequest) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceReadRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ResourceReadRequest) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type ResourceChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceChunk) Reset() {
	*x = ResourceChunk{}
	mi := &file_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChunk) ProtoMessage() {}

func (x *ResourceChunk) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChunk.ProtoReflect.Descriptor instead.
func (*ResourceChunk) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ResourceChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_resource_proto protoreflect.FileDescriptor

const file_resource_proto_rawDesc = "" +
	"\n" +
	"\x0eresource.proto\x12\x12brickly.runtime.v1\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\x13ResourceStatRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"8\n" +
	"\x15ResourceRevokeRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\x88\x01\n" +
	"\x10ResourceMetadata\x12;\n" +
	"\bresource\x18\x01 \x01(\v2\x1f.brickly.runtime.v1.ResourceRefR\bresource\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.brickly.runtime.v1.ResourceStateR\x05state\"\xa1\x02\n" +
	"\x14ResourceCreateHeader\x12\"\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tH\x00R\tmediaType\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x123\n" +
	"\x13expected_size_bytes\x18\x03 \x01(\x04H\x02R\x11expectedSizeBytes\x88\x01\x01\x12,\n" +
	"\x0fexpected_sha256\x18\x04 \x01(\fH\x03R\x0eexpectedSha256\x88\x01\x01\x12\x1a\n" +
	"\x06ttl_ms\x18\x05 \x01(\x04H\x04R\x05ttlMs\x88\x01\x01B\r\n" +
	"\v_media_typeB\a\n" +
	"\x05_nameB\x16\n" +
	"\x14_expected_size_bytesB\x12\n" +
	"\x10_expected_sha256B\t\n" +
	"\a_ttl_ms\"@\n" +
	"\x12ResourceWriteChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xa0\x01\n" +
	"\x12ResourceWriteFrame\x12B\n" +
	"\x06header\x18\x01 \x01(\v2(.brickly.runtime.v1.ResourceCreateHeaderH\x00R\x06header\x12>\n" +
	"\x05chunk\x18\x02 \x01(\v2&.brickly.runtime.v1.ResourceWriteChunkH\x00R\x05chunkB\x06\n" +
	"\x04body\"v\n" +
	"\x13ResourceReadRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1b\n" +
	"\x06length\x18\x03 \x01(\x04H\x00R\x06length\x88\x01\x01B\t\n" +
	"\a_length\";\n" +
	"\rResourceChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*\x85\x01\n" +
	"\rResourceState\x12\x1e\n" +
	"\x1aRESOURCE_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RESOURCE_STATE_AVAILABLE\x10\x01\x12\x1a\n" +
	"\x16RESOURCE_STATE_EXPIRED\x10\x02\x12\x1a\n" +
	"\x16RESOURCE_STATE_REVOKED\x10\x032\xe0\x02\n" +
	"\x0fResourceService\x12S\n" +
	"\x06Create\x12&.brickly.runtime.v1.ResourceWriteFrame\x1a\x1f.brickly.runtime.v1.ResourceRef(\x01\x12T\n" +
	"\x04Read\x12'.brickly.runtime.v1.ResourceReadRequest\x1a!.brickly.runtime.v1.ResourceChunk0\x01\x12U\n" +
	"\x04Stat\x12'.brickly.runtime.v1.ResourceStatRequest\x1a$.brickly.runtime.v1.ResourceMetadata\x12K\n" +
	"\x06Revoke\x12).brickly.runtime.v1.ResourceRevokeRequest\x1a\x16.google.protobuf.EmptyB\xc4\x01\n" +
	"\x16com.brickly.runtime.v1B\rResourceProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_resource_proto_rawDescOnce sync.Once
	file_resource_proto_rawDescData []byte
)

func file_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)))
	})
	return file_resource_proto_rawDescData
}

var file_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_resource_proto_goTypes = []any{
	(ResourceState)(0),            // 0: brickly.runtime.v1.ResourceState
	(*ResourceStatRequest)(nil),   // 1: brickly.runtime.v1.ResourceStatRequest
	(*ResourceRevokeRequest)(nil), // 2: brickly.runtime.v1.ResourceRevokeRequest
	(*ResourceMetadata)(nil),      // 3: brickly.runtime.v1.ResourceMetadata
	(*ResourceCreateHeader)(nil),  // 4: brickly.runtime.v1.ResourceCreateHeader
	(*ResourceWriteChunk)(nil),    // 5: brickly.runtime.v1.ResourceWriteChunk
	(*ResourceWriteFrame)(nil),    // 6: brickly.runtime.v1.ResourceWriteFrame
	(*ResourceReadRequest)(nil),   // 7: brickly.runtime.v1.ResourceReadRequest
	(*ResourceChunk)(nil),         // 8: brickly.runtime.v1.ResourceChunk
	(*ResourceRef)(nil),           // 9: brickly.runtime.v1.ResourceRef
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_resource_proto_depIdxs = []int32{
	9,  // 0: brickly.runtime.v1.ResourceMetadata.resource:type_name -> brickly.runtime.v1.ResourceRef
	0,  // 1: brickly.runtime.v1.ResourceMetadata.state:type_name -> brickly.runtime.v1.ResourceState
	4,  // 2: brickly.runtime.v1.ResourceWriteFrame.header:type_name -> brickly.runtime.v1.ResourceCreateHeader
	5,  // 3: brickly.runtime.v1.ResourceWriteFrame.chunk:type_name -> brickly.runtime.v1.ResourceWriteChunk
	6,  // 4: brickly.runtime.v1.ResourceService.Create:input_type -> brickly.runtime.v1.ResourceWriteFrame
	7,  // 5: brickly.runtime.v1.ResourceService.Read:input_type -> brickly.runtime.v1.ResourceReadRequest
	1,  // 6: brickly.runtime.v1.ResourceService.Stat:input_type -> brickly.runtime.v1.ResourceStatRequest
	2,  // 7: brickly.runtime.v1.ResourceService.Revoke:input_type -> brickly.runtime.v1.ResourceRevokeRequest
	9,  // 8: brickly.runtime.v1.ResourceService.Create:output_type -> brickly.runtime.v1.ResourceRef
	8,  // 9: brickly.runtime.v1.ResourceService.Read:output_type -> brickly.runtime.v1.ResourceChunk
	3,  // 10: brickly.runtime.v1.ResourceService.Stat:output_type -> brickly.runtime.v1.ResourceMetadata
	10, // 11: brickly.runtime.v1.ResourceService.Revoke:output_type -> google.protobuf.Empty
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_resource_proto_init() }
func file_resource_proto_init() {
	if File_resource_proto != nil {
		return
	}
	file_common_proto_init()
	file_resource_proto_msgTypes[3].OneofWrappers = []any{}
	file_resource_proto_msgTypes[5].OneofWrappers = []any{
		(*ResourceWriteFrame_Header)(nil),
		(*ResourceWriteFrame_Chunk)(nil),
	}
	file_resource_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_depIdxs,
		EnumInfos:         file_resource_proto_enumTypes,
		MessageInfos:      file_resource_proto_msgTypes,
	}.Build()
	File_resource_proto = out.File
	file_resource_proto_goTypes = nil
	file_resource_proto_depIdxs = nil
}
