// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: resource.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceService_Create_FullMethodName = "/brickly.runtime.v1.ResourceService/Create"
	ResourceService_Read_FullMethodName   = "/brickly.runtime.v1.ResourceService/Read"
	ResourceService_Stat_FullMethodName   = "/brickly.runtime.v1.ResourceService/Stat"
	ResourceService_Revoke_FullMethodName = "/brickly.runtime.v1.ResourceService/Revoke"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResourceService 是 Host 平台服务，不经过 InvocationGateway。
// 它仍经过 Runtime 身份、权限、配额和 Trace interceptor。
type ResourceServiceClient interface {
	Create(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResourceWriteFrame, ResourceRef], error)
	Read(ctx context.Context, in *ResourceReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceChunk], error)
	Stat(ctx context.Context, in *ResourceStatRequest, opts ...grpc.CallOption) (*ResourceMetadata, error)
	Revoke(ctx context.Context, in *ResourceRevokeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) Create(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResourceWriteFrame, ResourceRef], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[0], ResourceService_Create_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResourceWriteFrame, ResourceRef]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_CreateClient = grpc.ClientStreamingClient[ResourceWriteFrame, ResourceRef]

func (c *resourceServiceClient) Read(ctx context.Context, in *ResourceReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceService_ServiceDesc.Streams[1], ResourceService_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResourceReadRequest, ResourceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_ReadClient = grpc.ServerStreamingClient[ResourceChunk]

func (c *resourceServiceClient) Stat(ctx context.Context, in *ResourceStatRequest, opts ...grpc.CallOption) (*ResourceMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceMetadata)
	err := c.cc.Invoke(ctx, ResourceService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) Revoke(ctx context.Context, in *ResourceRevokeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ResourceService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
//
// ResourceService 是 Host 平台服务，不经过 InvocationGateway。
// 它仍经过 Runtime 身份、权限、配额和 Trace interceptor。
type ResourceServiceServer interface {
	Create(grpc.ClientStreamingServer[ResourceWriteFrame, ResourceRef]) error
	Read(*ResourceReadRequest, grpc.ServerStreamingServer[ResourceChunk]) error
	Stat(context.Context, *ResourceStatRequest) (*ResourceMetadata, error)
	Revoke(context.Context, *ResourceRevokeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) Create(grpc.ClientStreamingServer[ResourceWriteFrame, ResourceRef]) error {
	return status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedResourceServiceServer) Read(*ResourceReadRequest, grpc.ServerStreamingServer[ResourceChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedResourceServiceServer) Stat(context.Context, *ResourceStatRequest) (*ResourceMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedResourceServiceServer) Revoke(context.Context, *ResourceRevokeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResourceServiceServer).Create(&grpc.GenericServerStream[ResourceWriteFrame, ResourceRef]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_CreateServer = grpc.ClientStreamingServer[ResourceWriteFrame, ResourceRef]

func _ResourceService_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResourceReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).Read(m, &grpc.GenericServerStream[ResourceReadRequest, ResourceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceService_ReadServer = grpc.ServerStreamingServer[ResourceChunk]

func _ResourceService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).Stat(ctx, req.(*ResourceStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).Revoke(ctx, req.(*ResourceRevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brickly.runtime.v1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _ResourceService_Stat_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _ResourceService_Revoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _ResourceService_Create_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _ResourceService_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "resource.proto",
}
