// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageKeyRequest) Reset() {
	*x = StorageKeyRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageKeyRequest) ProtoMessage() {}

func (x *StorageKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageKeyRequest.ProtoReflect.Descriptor instead.
func (*StorageKeyRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StorageKeyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StorageKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StorageSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *BrickValue            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageSetRequest) Reset() {
	*x = StorageSetRequest{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSetRequest) ProtoMessage() {}

func (x *StorageSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSetRequest.ProtoReflect.Descriptor instead.
func (*StorageSetRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StorageSetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StorageSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageSetRequest) GetValue() *BrickValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type StorageValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *BrickValue            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageValue) Reset() {
	*x = StorageValue{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageValue) ProtoMessage() {}

func (x *StorageValue) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageValue.ProtoReflect.Descriptor instead.
func (*StorageValue) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StorageValue) GetValue() *BrickValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageValue) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x12brickly.runtime.v1\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x11StorageKeyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"y\n" +
	"\x11StorageSetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x03 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05value\"Z\n" +
	"\fStorageValue\x124\n" +
	"\x05value\x18\x01 \x01(\v2\x1e.brickly.runtime.v1.BrickValueR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\xef\x01\n" +
	"\x0eStorageService\x12N\n" +
	"\x03Get\x12%.brickly.runtime.v1.StorageKeyRequest\x1a .brickly.runtime.v1.StorageValue\x12D\n" +
	"\x03Set\x12%.brickly.runtime.v1.StorageSetRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x06Delete\x12%.brickly.runtime.v1.StorageKeyRequest\x1a\x16.google.protobuf.EmptyB\xc3\x01\n" +
	"\x16com.brickly.runtime.v1B\fStorageProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_storage_proto_goTypes = []any{
	(*StorageKeyRequest)(nil), // 0: brickly.runtime.v1.StorageKeyRequest
	(*StorageSetRequest)(nil), // 1: brickly.runtime.v1.StorageSetRequest
	(*StorageValue)(nil),      // 2: brickly.runtime.v1.StorageValue
	(*BrickValue)(nil),        // 3: brickly.runtime.v1.BrickValue
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_storage_proto_depIdxs = []int32{
	3, // 0: brickly.runtime.v1.StorageSetRequest.value:type_name -> brickly.runtime.v1.BrickValue
	3, // 1: brickly.runtime.v1.StorageValue.value:type_name -> brickly.runtime.v1.BrickValue
	0, // 2: brickly.runtime.v1.StorageService.Get:input_type -> brickly.runtime.v1.StorageKeyRequest
	1, // 3: brickly.runtime.v1.StorageService.Set:input_type -> brickly.runtime.v1.StorageSetRequest
	0, // 4: brickly.runtime.v1.StorageService.Delete:input_type -> brickly.runtime.v1.StorageKeyRequest
	2, // 5: brickly.runtime.v1.StorageService.Get:output_type -> brickly.runtime.v1.StorageValue
	4, // 6: brickly.runtime.v1.StorageService.Set:output_type -> google.protobuf.Empty
	4, // 7: brickly.runtime.v1.StorageService.Delete:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
