// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: window.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWindowBoundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWindowBoundsRequest) Reset() {
	*x = GetWindowBoundsRequest{}
	mi := &file_window_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWindowBoundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWindowBoundsRequest) ProtoMessage() {}

func (x *GetWindowBoundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWindowBoundsRequest.ProtoReflect.Descriptor instead.
func (*GetWindowBoundsRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{0}
}

func (x *GetWindowBoundsRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type SubscribeWindowStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeWindowStateRequest) Reset() {
	*x = SubscribeWindowStateRequest{}
	mi := &file_window_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeWindowStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeWindowStateRequest) ProtoMessage() {}

func (x *SubscribeWindowStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeWindowStateRequest.ProtoReflect.Descriptor instead.
func (*SubscribeWindowStateRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeWindowStateRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type WindowBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowBounds) Reset() {
	*x = WindowBounds{}
	mi := &file_window_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowBounds) ProtoMessage() {}

func (x *WindowBounds) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowBounds.ProtoReflect.Descriptor instead.
func (*WindowBounds) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{2}
}

func (x *WindowBounds) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WindowBounds) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WindowBounds) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *WindowBounds) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type WindowStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Bounds        *WindowBounds          `protobuf:"bytes,2,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Focused       bool                   `protobuf:"varint,3,opt,name=focused,proto3" json:"focused,omitempty"`
	Destroyed     bool                   `protobuf:"varint,4,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowStateEvent) Reset() {
	*x = WindowStateEvent{}
	mi := &file_window_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowStateEvent) ProtoMessage() {}

func (x *WindowStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowStateEvent.ProtoReflect.Descriptor instead.
func (*WindowStateEvent) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{3}
}

func (x *WindowStateEvent) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *WindowStateEvent) GetBounds() *WindowBounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *WindowStateEvent) GetFocused() bool {
	if x != nil {
		return x.Focused
	}
	return false
}

func (x *WindowStateEvent) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

var File_window_proto protoreflect.FileDescriptor

const file_window_proto_rawDesc = "" +
	"\n" +
	"\fwindow.proto\x12\x12brickly.runtime.v1\"5\n" +
	"\x16GetWindowBoundsRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\":\n" +
	"\x1bSubscribeWindowStateRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\"X\n" +
	"\fWindowBounds\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xa1\x01\n" +
	"\x10WindowStateEvent\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x128\n" +
	"\x06bounds\x18\x02 \x01(\v2 .brickly.runtime.v1.WindowBoundsR\x06bounds\x12\x18\n" +
	"\afocused\x18\x03 \x01(\bR\afocused\x12\x1c\n" +
	"\tdestroyed\x18\x04 \x01(\bR\tdestroyed2\xd5\x01\n" +
	"\rWindowService\x12Y\n" +
	"\tGetBounds\x12*.brickly.runtime.v1.GetWindowBoundsRequest\x1a .brickly.runtime.v1.WindowBounds\x12i\n" +
	"\x0eSubscribeState\x12/.brickly.runtime.v1.SubscribeWindowStateRequest\x1a$.brickly.runtime.v1.WindowStateEvent0\x01B\xc2\x01\n" +
	"\x16com.brickly.runtime.v1B\vWindowProtoP\x01Z1github.com/836145715/brickly-sdk-go/internal/grpc\xa2\x02\x03BRX\xaa\x02\x12Brickly.Runtime.V1\xca\x02\x12Brickly\\Runtime\\V1\xe2\x02\x1eBrickly\\Runtime\\V1\\GPBMetadata\xea\x02\x14Brickly::Runtime::V1b\x06proto3"

var (
	file_window_proto_rawDescOnce sync.Once
	file_window_proto_rawDescData []byte
)

func file_window_proto_rawDescGZIP() []byte {
	file_window_proto_rawDescOnce.Do(func() {
		file_window_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_window_proto_rawDesc), len(file_window_proto_rawDesc)))
	})
	return file_window_proto_rawDescData
}

var file_window_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_window_proto_goTypes = []any{
	(*GetWindowBoundsRequest)(nil),      // 0: brickly.runtime.v1.GetWindowBoundsRequest
	(*SubscribeWindowStateRequest)(nil), // 1: brickly.runtime.v1.SubscribeWindowStateRequest
	(*WindowBounds)(nil),                // 2: brickly.runtime.v1.WindowBounds
	(*WindowStateEvent)(nil),            // 3: brickly.runtime.v1.WindowStateEvent
}
var file_window_proto_depIdxs = []int32{
	2, // 0: brickly.runtime.v1.WindowStateEvent.bounds:type_name -> brickly.runtime.v1.WindowBounds
	0, // 1: brickly.runtime.v1.WindowService.GetBounds:input_type -> brickly.runtime.v1.GetWindowBoundsRequest
	1, // 2: brickly.runtime.v1.WindowService.SubscribeState:input_type -> brickly.runtime.v1.SubscribeWindowStateRequest
	2, // 3: brickly.runtime.v1.WindowService.GetBounds:output_type -> brickly.runtime.v1.WindowBounds
	3, // 4: brickly.runtime.v1.WindowService.SubscribeState:output_type -> brickly.runtime.v1.WindowStateEvent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_window_proto_init() }
func file_window_proto_init() {
	if File_window_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_window_proto_rawDesc), len(file_window_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_window_proto_goTypes,
		DependencyIndexes: file_window_proto_depIdxs,
		MessageInfos:      file_window_proto_msgTypes,
	}.Build()
	File_window_proto = out.File
	file_window_proto_goTypes = nil
	file_window_proto_depIdxs = nil
}
