// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: window.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WindowService_GetBounds_FullMethodName      = "/brickly.runtime.v1.WindowService/GetBounds"
	WindowService_SubscribeState_FullMethodName = "/brickly.runtime.v1.WindowService/SubscribeState"
)

// WindowServiceClient is the client API for WindowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WindowService 推送窗口状态，不由 SDK 轮询。
type WindowServiceClient interface {
	GetBounds(ctx context.Context, in *GetWindowBoundsRequest, opts ...grpc.CallOption) (*WindowBounds, error)
	SubscribeState(ctx context.Context, in *SubscribeWindowStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WindowStateEvent], error)
}

type windowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWindowServiceClient(cc grpc.ClientConnInterface) WindowServiceClient {
	return &windowServiceClient{cc}
}

func (c *windowServiceClient) GetBounds(ctx context.Context, in *GetWindowBoundsRequest, opts ...grpc.CallOption) (*WindowBounds, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindowBounds)
	err := c.cc.Invoke(ctx, WindowService_GetBounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowServiceClient) SubscribeState(ctx context.Context, in *SubscribeWindowStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WindowStateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WindowService_ServiceDesc.Streams[0], WindowService_SubscribeState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeWindowStateRequest, WindowStateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WindowService_SubscribeStateClient = grpc.ServerStreamingClient[WindowStateEvent]

// WindowServiceServer is the server API for WindowService service.
// All implementations must embed UnimplementedWindowServiceServer
// for forward compatibility.
//
// WindowService 推送窗口状态，不由 SDK 轮询。
type WindowServiceServer interface {
	GetBounds(context.Context, *GetWindowBoundsRequest) (*WindowBounds, error)
	SubscribeState(*SubscribeWindowStateRequest, grpc.ServerStreamingServer[WindowStateEvent]) error
	mustEmbedUnimplementedWindowServiceServer()
}

// UnimplementedWindowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWindowServiceServer struct{}

func (UnimplementedWindowServiceServer) GetBounds(context.Context, *GetWindowBoundsRequest) (*WindowBounds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBounds not implemented")
}
func (UnimplementedWindowServiceServer) SubscribeState(*SubscribeWindowStateRequest, grpc.ServerStreamingServer[WindowStateEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeState not implemented")
}
func (UnimplementedWindowServiceServer) mustEmbedUnimplementedWindowServiceServer() {}
func (UnimplementedWindowServiceServer) testEmbeddedByValue()                       {}

// UnsafeWindowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WindowServiceServer will
// result in compilation errors.
type UnsafeWindowServiceServer interface {
	mustEmbedUnimplementedWindowServiceServer()
}

func RegisterWindowServiceServer(s grpc.ServiceRegistrar, srv WindowServiceServer) {
	// If the following call pancis, it indicates UnimplementedWindowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WindowService_ServiceDesc, srv)
}

func _WindowService_GetBounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWindowBoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowServiceServer).GetBounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WindowService_GetBounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowServiceServer).GetBounds(ctx, req.(*GetWindowBoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowService_SubscribeState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeWindowStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WindowServiceServer).SubscribeState(m, &grpc.GenericServerStream[SubscribeWindowStateRequest, WindowStateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WindowService_SubscribeStateServer = grpc.ServerStreamingServer[WindowStateEvent]

// WindowService_ServiceDesc is the grpc.ServiceDesc for WindowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WindowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brickly.runtime.v1.WindowService",
	HandlerType: (*WindowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBounds",
			Handler:    _WindowService_GetBounds_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeState",
			Handler:       _WindowService_SubscribeState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "window.proto",
}
